import React from 'react'

export const TermsConditionsPage = () => {
  return (
    <section className="container mb-5 pt-4 pb-2 py-mg-4">
      <div className="row gy-4">
        {/* Content */}
        <div className="col-lg-9">
          <h2 className="h1">Términos y condiciones</h2>
          <p className="mb-4 pb-2">Atemporal AC</p>
          {/* Video */}
          <div className="gallery mb-4 pb-2" data-video="true">
            <a href="https://www.youtube.com/watch?v=LDb-G8y88Sc" className="gallery-item video-item is-hovered rounded-3">
              <img src="assets/img/home/bg1.jpg" alt="Video preview" />
            </a>
          </div>
          <h3 className="h3">1. Aceptación de estos términos</h3>
          <h4 className="h4">1.1 Qué es qué.</h4>
          <p className="mb-4 pb-2">Los productos, características y ofertas de Atemporal están disponibles (a) en línea a través de varias propiedades de Atemporal, incluidos sin limitación Atemporal, (b) fuera de la plataforma, incluidos, entre otros, los servicios de RFID, gestión de acceso, patrocinio y marketing o distribución; y (c) a través de aplicaciones móviles, páginas web, interfaces de programación de aplicaciones y subdominios (&#34;Aplicaciones&#34;). (a), (b) y (c) se denominan colectivamente &#34;Propiedades de Atemporal&#34; o nuestros &#34;Servicios&#34;. Estos Términos se aplican a cualquier Sitio en el que se publican; donde en su lugar se publican otros términos o acuerdos, dichos términos o acuerdos se aplican en la medida en que entren en conflicto con estos Términos. El material, incluidos, sin limitación, la información, los datos, el texto, el contenido editorial, los elementos de diseño, el aspecto, el formato, los gráficos, las imágenes, las fotografías, los vídeos, la música, los sonidos y otro tipo de contenido incluido o entregado a través de los Servicios o puesto a disposición de otro modo por Atemporal en relación con los Servicios es el &#34;Contenido del sitio&#34; (o &#34;Contenido&#34;). Cualquier material (incluidas las categorías anteriores) que contribuyas, proporciones, publiques o pongas a disposición mediante los Servicios es &#34;Tu contenido&#34;.</p>
          <h4 className="h4">1.2 Quién es quién.</h4>
          <p className="mb-4 pb-2">Cuando estos Términos utilizan el término &#34;Organizador&#34; nos referimos a creadores de eventos que utilizan los Servicios para crear eventos mostrados en nuestros Servicios (a) para consumir información o asistir a Eventos (&#34;Consumidores&#34;), o (b) con cualquier otro fin. Los Organizadores, los Consumidores y los terceros que utilizan nuestros Servicios se mencionan colectivamente en estos Términos como &#34;Usuarios&#34;, &#34;tú&#34;, &#34;ti&#34; o &#34;tu&#34;.</p>
          <p className="mb-4 pb-2">Cuando estos Términos mencionan &#34;Atemporal&#34;, &#34;nosotros&#34;, &#34;nos&#34; o &#34;nuestro&#34;, se refiere a Atemporal A.C. y sus afiliados y subsidiarios, y a cada uno de los respectivos funcionarios, directores, agentes, socios. y empleados. Los Afiliados incluyen, entre otros, Atemporal. La entidad contratante al otro lado de estos Términos es la siguiente:</p>
         {/* Actualizar informacion sobre el metodo de pago */}
          <ol>Si eres un Consumidor ubicado en México y presentas una tarjeta de crédito para que Atemporal procese tu compra, solo para el procesamiento de pagos de Atemporal, contratarás con Sr. Pago, con domicilio social en “Dirección de Sr Pago).</ol>
          <p className="mb-4 pb-2">Ten en cuenta que independientemente de la entidad con la que contrates para el procesamiento de pagos de Atemporal, todos los demás servicios ofrecidos por Atemporal se ofrecen a través de tu entidad local. Si cambias tu lugar de residencia, la empresa Atemporal con la que contrates se determinará por tu nuevo lugar de residencia según lo especificado anteriormente a partir de la fecha en que cambies tu lugar de residencia.</p>
          <h4 className="h4">1.3 Qué más.</h4>
          <p className="mb-4 pb-2">Si eres un Organizador que ofrece eventos con boletos pago, también te serán aplicables el Acuerdo comercial y los Requisitos de la política de reembolsos para los organizadores de Atemporal. Si eres un Organizador o Consumidor, te serán aplicables las Directrices de la comunidad de Atemporal. (Algunos de los términos en esos acuerdos están duplicados en estos Términos de servicio, pero no todos). Si eres un tercero que interactúa con nuestros Servicios no como un Organizador o un Consumidor, es posible que te sean aplicables los Términos de uso de API o la Política sobre marcas comerciales y derechos de autor. Pon atención a los términos y condiciones adicionales que se muestran con ciertos Servicios que puedas utilizar de vez en cuando, ya que también te serán aplicables. Y, al aceptar estos Términos de servicio, reconoces que has leído la Política de privacidad y la Declaración de cookies aplicable a todos los Usuarios. A veces podemos proporcionarte servicios que no se describen en estos Términos de servicio, o servicios personalizados: a menos que hayamos celebrado un acuerdo separado y firmado que sustituya expresamente estos Términos de servicio, estos Términos de servicio se aplicarán también a esos servicios.</p>
          <h4 className="h4">1.4 Qué significan los &#34;Términos de servicio&#34;.</h4>
          <p className="mb-4 pb-2">Estos Términos de servicio y los demás documentos a los que se hace referencia (incluida la Sección 1.3 anterior) incluyen los &#34;Términos&#34; de Atemporal. Estos Términos son un acuerdo legalmente vinculante entre tú y Atemporal que rige tu acceso y uso de los Servicios y establece tus derechos y responsabilidades cuando utilizas los Servicios. Al utilizar cualquiera de nuestros Servicios (incluida la navegación en un Sitio), aceptas estos Términos. Si no aceptas estos Términos, no utilices los Servicios ni accedas a ellos. Si vas a utilizar los Servicios en nombre de una entidad (como en nombre de tu empleador), aceptas los presentes Términos en nombre de dicha entidad y sus filiales, y declaras que tienes facultad para hacerlo. En tal caso, las referencias a &#34;tú&#34; y &#34;tu&#34; se referirán a dicha entidad.</p>

          <h3 className="h3">2. Servicios y rol de Atemporal</h3>
          <h4 className="h4">2.1 Lo que hacemos. </h4>
          <p className="mb-4 pb-2">Los Servicios de Atemporal ofrecen una manera rápida y sencilla para que los Organizadores creen perfiles de ponentes, perfiles de organizadores y otras páginas web relacionadas con sus eventos, promocionen estas páginas web y los eventos a los visitantes o navegadores en los Servicios o en cualquier otro lugar en línea, gestionen boletos y registros en línea o in situ, soliciten donaciones y vendan o reserven artículos promocionales o alojamientos relacionados con esos eventos a Consumidores o a Usuarios. Las descripciones de otros servicios más específicos generalmente pueden encontrarse en el Sitio de cada una de las Propiedades de Atemporal.</p>
          <h4 className="h4">2.2 Cómo encajamos.</h4>
          <p className="mb-4 pb-2">Atemporal no es el creador, organizador ni el propietario de los eventos listados en los Servicios. Por el contrario, Atemporal proporciona sus Servicios, que permiten a los Organizadores gestionar la venta de boletos y el registro y promocionar sus eventos. El Organizador es el único responsable de garantizar que cualquier página que muestre un evento en los Servicios (y el evento mismo) cumpla todas las leyes, normas y reglamentaciones locales, estatales, provinciales, nacionales y de otro tipo, y que los bienes y servicios descritos en la página del evento se entreguen como se describe y de una manera satisfactoria y precisa. El Organizador de un evento de pago selecciona el método de procesamiento de pagos para su evento como se describe más detalladamente en el Acuerdo comercial. Los Consumidores deben utilizar cualquier método de procesamiento de pagos que seleccione el Organizador. Si el Organizador selecciona un método de procesamiento de pagos que utilice un tercero para procesar los pagos, ni Atemporal ni sus socios de procesamiento de pagos procesarán la transacción, sino que transmitiremos los detalles de pago del Consumidor al proveedor de servicios de pago designado por el Organizador. Si un Organizador usa el procesamiento de pagos de Atemporal (como se define en el Acuerdo comercial), Atemporal actúa también como el agente limitado del Organizador únicamente para el fin de usar a nuestros proveedores de servicios de pago externos para cobrar pagos realizados por Consumidores en los Servicios y pasar tales pagos al Organizador.</p>

          <h3 className="h3">3. Privacidad e información del Consumidor</h3>
          <p className="mb-4 pb-2">3.1  Sabemos que tu información personal es importante para ti, y también es importante para Atemporal. La información proporcionada a Atemporal por los Usuarios o recopilada por Atemporal a través de las Propiedades de Atemporal, se rige por nuestra Política de privacidad.</p>
          <p className="mb-4 pb-2">3.2  Si eres un Organizador, declaras, garantizas y aceptas que (a) cumplirás en todo momento todas las leyes, normas y reglamentaciones locales, estatales, provinciales, nacionales y de otro tipo con respecto a la información que recopiles (o recibas sobre) consumidores, y (b) cumplirás en todo momento las políticas aplicables publicadas en los Servicios con respecto a la información que recopiles de (o recibas sobre) los consumidores.</p>

          <h3 className="h3">4. Vigencia y finalización</h3>
          <p className="mb-4 pb-2">4.1 Estos Términos se te aplican tan pronto como accedas a los Servicios por cualquier medio y continúan en vigor hasta que finalicen. Puede llegar el momento en que tú o Atemporal decidan que es mejor separarse, como se describe en las Secciones 4.2 o 4.3 a continuación. Cuando eso sucede, estos Términos generalmente ya no se aplicarán. Sin embargo, como se describe en la Sección 4.4, ciertas disposiciones siempre serán aplicables tanto a ti como a Atemporal.</p>
          <p className="mb-4 pb-2">4.2 Atemporal puede rescindir tu derecho a utilizar los Servicios en cualquier momento (a) si infringes o incumples estos Términos; (b) si haces un uso incorrecto o mal uso de los Servicios, o utilizas los Servicios de una manera no prevista o permitida por Atemporal; o (c) si permitirte el acceso y uso de los Servicios infringiese cualquier ley, reglamentación y regulación local, estatal, provincial, nacional y de otro tipo, o expusiese a Atemporal a responsabilidad legal. Atemporal puede optar por dejar de ofrecer los Servicios, o cualquier porción particular del Servicio, o modificar o reemplazar cualquier aspecto del Servicio, en cualquier momento. Haremos todos los esfuerzos razonables para enviarte un aviso de nuestra cancelación de tu acceso a los Servicios, donde, a exclusivo criterio de Atemporal, no hacerlo te perjudicaría sustancialmente. Aceptas que Atemporal no será responsable ante ti o ante otra parte de cualquier finalización de tu derecho a utilizar o, de otro modo, acceder a los Servicios.</p>
           <p className="mb-4 pb-2">4.3 Salvo en la medida en que hayas acordado lo contrario mediante un acuerdo aparte por escrito entre tú y Atemporal, puedes poner fin a tu acceso a los Servicios y la aplicabilidad general de los Términos cerrando tu cuenta. Si eres un Consumidor que utiliza los Servicios sin una cuenta registrada, tu única opción para que estos Términos ya no se apliquen es dejar de acceder a los Servicios de forma indefinida. Siempre y cuando continúes accediendo a los Servicios, incluso sin una cuenta, estos Términos seguirán vigentes. Si existe un acuerdo aparte entre tú y Atemporal que rija el uso que haces de los Servicios y dicho acuerdo finaliza o vence, estos presentes Términos (sin la modificación que implique tal acuerdo) regirán el uso que hagas de los Servicios hasta tal terminación o rescisión.</p>
           <p className="mb-4 pb-2">4.4 Todas las disposiciones de estos Términos que, por su naturaleza, deban permanecer vigentes tras la finalización de estos Términos, perdurarán (incluidas, entre otras, todas las limitaciones sobre la responsabilidad, las exenciones, las obligaciones de indemnización, las exclusiones de garantías, los acuerdos de arbitraje, la elección de tribunal y foro judicial, y las licencias y protección de la propiedad intelectual).</p>

           <h3 className="h3">5. Controles de exportación y países restringidos.</h3>
           <p className="mb-4 pb-2">Como empresa global con sede en México con operaciones en otros países, Atemporal cumple ciertos controles de exportación y leyes de sanciones económicas. Todos los usuarios, independientemente de su ubicación o la ubicación del evento, deben familiarizarse con estas restricciones. Al aceptar estos Términos, declaras y garantizas lo siguiente: (a) no te encuentras en un país al que EE. UU., Reino Unido, la Unión Europea, Australia o Canadá haya embargado bienes y/o servicios del mismo tipo que los Servicios, incluidos entre otros Cuba, Irán, Corea del Norte, Siria o la región de Crimea de Ucrania; y (b) no eres una persona o entidad que sea propiedad de o esté bajo el control de, o afiliada a una persona o entidad que aparezca en (i) la lista de evasores de sanciones del extranjero, la lista del consejo legislativo palestino o la lista de nacionales especialmente designados de la U.S. Office of Foreign Assets Control (oficina de control de activos extranjeros de EE. UU.); la lista de exclusión de terroristas del U.S. Department of State (departamento de estado de EE. UU.); la lista de personas o entidades no autorizadas, o la lista no verificada del Departamento de industria y seguridad; la lista consolidada de objetivos publicada por el Departamento de Relaciones Exteriores y Comerciales de Australia; (ii) que esté sujeta a sanciones en cualquier otro país; o (iii) que esté implicada en el diseño, desarrollo o producción de vehículos aéreos no tripulados, misiles o armas nucleares, biológicas o químicas.</p>

           <h3 className="h3">6. Exoneración e indemnización.</h3>
           <p className="mb-4 pb-2">Aquí es donde aceptas cubrir a Atemporal si utilizas el Servicio de alguna manera por la que Atemporal sea objeto de un asunto legal, o deba afrontar otras reclamaciones o gastos, o según lo establecido aquí, en la medida en que lo permitan las leyes aplicables.</p>
           <h4 className="h4">6.1 Exoneración.</h4>
           <p className="mb-4 pb-2">Por el presente documento aceptas exonerar a Atemporal de todos los daños (ya sean directos, indirectos, fortuitos, consecuentes o de otro tipo), pérdidas, responsabilidades, costos y gastos de cualquier tipo y naturaleza, conocidos y desconocidos, que surjan de algún modo de disputas entre tú y terceros (incluidos otros Usuarios), o estén relacionados con estas, en lo relativo a los Servicios u otro evento indicado en los Servicios. Además, renuncias a cualquier ley o estatuto aplicable, que, en esencia, especifique lo siguiente: &#34;UNA EXONERACIÓN GENERAL NO SE EXTIENDE A LAS RECLAMACIONES QUE EL ACREEDOR DESCONOCE O NO SOSPECHA QUE EXISTAN A SU FAVOR EN EL MOMENTO DE EJECUTAR LA EXONERACIÓN, LAS CUALES, DE HABERSE CONOCIDO, AFECTARÍAN MATERIALMENTE A SU LIQUIDACIÓN CON EL DEUDOR&#34;.</p>
           <h4 className="h4">6.2 Indemnización.</h4>
           <p className="mb-4 pb-2">Aceptas defender, indemnizar y liberar de responsabilidades a Atemporal y a cada uno de sus funcionarios, directores, agentes, socios de marca compartida, licenciatarios, socios de procesamiento de pagos, otros socios y empleados respectivos de todos los daños (ya sean directos, indirectos, fortuitos, derivados o de otro tipo), pérdidas, responsabilidades, costos y gastos (incluidas, sin limitación, honorarios de contabilidad y abogados razonables) que resulten de cualquier reclamación, demanda, acción, procedimiento (ya sea ante un árbitro, tribunal, mediador u otro) o investigación realizada por cualquier tercero (cada una es una &#34;Reclamación&#34;) debida a o que surja de: (a) tu incumplimiento de estos Términos (incluidos los términos, acuerdos o políticas que se incorporen a estos Términos); (b) tu uso de los Servicios que incumplan estos Términos u otras políticas que publiquemos o facilitemos; (c) tu incumplimiento de las leyes, reglas y normativas locales, estatales, provinciales y nacionales aplicables o vulneración de los derechos de un tercero; (d) la recaudación y remisión de impuestos de Atemporal y (e) si eres un Organizador, tus eventos (incluso cuando Atemporal ofreció servicios con respecto a esos eventos), siempre que en caso de (e) esta indemnización no se aplicará en la medida en que la Reclamación surja de una negligencia o conducta indebida de Atemporal. Atemporal te notificará cualquier Reclamación de ese tipo, siempre que tus obligaciones aquí estipuladas no se vean limitadas si Atemporal no realizara la notificación o tardara en hacerlo, salvo en la medida en que te veas perjudicado desde el punto de vista material debido a dicho fallo. Además, en determinadas circunstancias Atemporal puede optar por gestionar la Reclamación por su propia cuenta, en cuyo caso aceptas cooperar con Atemporal de la manera que solicitemos.</p>
          <h4 className="h6">
            <i className="bx bx-plus-circle me-1 mt-n1 align-middle fs-5 text-primary" />
            PROS
          </h4>
          <ul className="mb-4 pb-2 ps-4">
            <li className="mb-1">A eu, ac nunc, volutpat. Augue enim ac justo, at elementum, arcu.</li>
            <li className="mb-1">At sodales quam felis ullamcorper iaculis tristique. Felis, etiam felis pellentesque sit neque.</li>
            <li className="mb-1">Porta ipsum quis lacus eu ipsum mattis sit quis. Massa, massa lectus porttitor laoreet ultricies odio fermentum arcu quam.</li>
            <li className="mb-1">Accumsan arcu neque, nisl, pellentesque fames justo consequat blandit lacus. Eget odio vel nulla vel.</li>
            <li className="mb-1">Diam ac phasellus est, eu urna purus blandit aliquam. Vitae accumsan et pellentesque diam in.</li>
            <li>Tellus arcu, lectus tincidunt neque nunc. Bibendum lacus, molestie ultrices sed arcu.</li>
          </ul>
          <h4 className="h6">
            <i className="bx bx-minus-circle me-1 mt-n1 align-middle fs-5 text-primary" />
            CONS
          </h4>
          <ul className="mb-4 pb-2 ps-4">
            <li className="mb-1">Donec maecenas justo, et tortor quam elementum pharetra velit. Auctor dictum purus sollicitudin et quam vehicula amet lacus, integer.</li>
            <li className="mb-1">Mi elit nibh erat facilisis. Volutpat eget malesuada mi in.</li>
            <li className="mb-1">Tincidunt iaculis eleifend arcu egestas. Sit gravida vestibulum quam scelerisque.</li>
            <li className="mb-1">Ornare elit, vel, ullamcorper nunc nulla pellentesque ut varius. Vitae tortor nulla a turpis erat fermentum, rhoncus.</li>
            <li>Gravida cursus nunc habitant aliquet lacus. Tempus, interdum nullam non quam ipsum ultricies ac.</li>
          </ul>
          <h2 className="h4">Conclusion</h2>
          <p className="mb-4 pb-2">Venenatis faucibus platea gravida amet sed sed urna volutpat. Aliquam neque, mi, justo odio semper. Egestas potentiquis neque nunc, rhoncus hendrerit. Viverra gravida pretium dolor eget placerat morbi proin eget. Vestibulum vitae ultrices vel sed sit quis. Ac quis diam at nulla libero. Turpis duis magna tellus condimentum.</p>
          <p className="mb-4 pb-2">Velit parturient tellus tellus, congue pulvinar tellus viverra. In&nbsp;cum massa mattis&nbsp;ac. Amet vitae massa ut&nbsp;mi&nbsp;etiam. Auctor aliquam tristique felis donec eu&nbsp;sit nisi. Accumsan mauris eget convallis mattis sed etiam scelerisque.</p>
        </div>
      </div>
    </section>
  )
}
