import React from 'react'
import './style.scss'

export const TermsConditionsPage = () => {
  return (
    <section className="container mb-5 pt-4 pb-2 py-mg-4">
      <div className="row gy-4">
        {/* Content */}
        <div className="col-lg-9">
          <h2 className="h1">Términos y condiciones</h2>
          <p className="mb-4 pb-2">Atemporal AC</p>
          {/* Video */}
          <div className="gallery mb-4 pb-2" data-video="true">
            <a href="https://www.youtube.com/watch?v=LDb-G8y88Sc" className="gallery-item video-item is-hovered rounded-3">
              <img src="assets/img/home/bg1.jpg" alt="Video preview" />
            </a>
          </div>
          <div className="texto-justificado">
          <h3 className="h3">1. Aceptación de estos términos</h3>
          <h4 className="h4">1.1 Qué es qué.</h4>
          <p className="mb-4 pb-2">Los productos, características y ofertas de Atemporal están disponibles (a) en línea a través de varias propiedades de Atemporal, incluidos sin limitación Atemporal, (b) fuera de la plataforma, incluidos, entre otros, los servicios de RFID, gestión de acceso, patrocinio y marketing o distribución; y (c) a través de aplicaciones móviles, páginas web, interfaces de programación de aplicaciones y subdominios (&#34;Aplicaciones&#34;). (a), (b) y (c) se denominan colectivamente &#34;Propiedades de Atemporal&#34; o nuestros &#34;Servicios&#34;. Estos Términos se aplican a cualquier Sitio en el que se publican; donde en su lugar se publican otros términos o acuerdos, dichos términos o acuerdos se aplican en la medida en que entren en conflicto con estos Términos. El material, incluidos, sin limitación, la información, los datos, el texto, el contenido editorial, los elementos de diseño, el aspecto, el formato, los gráficos, las imágenes, las fotografías, los vídeos, la música, los sonidos y otro tipo de contenido incluido o entregado a través de los Servicios o puesto a disposición de otro modo por Atemporal en relación con los Servicios es el &#34;Contenido del sitio&#34; (o &#34;Contenido&#34;). Cualquier material (incluidas las categorías anteriores) que contribuyas, proporciones, publiques o pongas a disposición mediante los Servicios es &#34;Tu contenido&#34;.</p>
          <h4 className="h4">1.2 Quién es quién.</h4>
          <p className="mb-4 pb-2">Cuando estos Términos utilizan el término &#34;Organizador&#34; nos referimos a creadores de eventos que utilizan los Servicios para crear eventos mostrados en nuestros Servicios (a) para consumir información o asistir a Eventos (&#34;Consumidores&#34;), o (b) con cualquier otro fin. Los Organizadores, los Consumidores y los terceros que utilizan nuestros Servicios se mencionan colectivamente en estos Términos como &#34;Usuarios&#34;, &#34;tú&#34;, &#34;ti&#34; o &#34;tu&#34;.</p>
          <p className="mb-4 pb-2">Cuando estos Términos mencionan &#34;Atemporal&#34;, &#34;nosotros&#34;, &#34;nos&#34; o &#34;nuestro&#34;, se refiere a Atemporal A.C. y sus afiliados y subsidiarios, y a cada uno de los respectivos funcionarios, directores, agentes, socios. y empleados. Los Afiliados incluyen, entre otros, Atemporal. La entidad contratante al otro lado de estos Términos es la siguiente:</p>
         {/* Actualizar informacion sobre el metodo de pago */}
          <ol>Si eres un Consumidor ubicado en México y presentas una tarjeta de crédito para que Atemporal procese tu compra, solo para el procesamiento de pagos de Atemporal, contratarás con Sr. Pago, con domicilio social en “Dirección de Sr Pago).</ol>
          <p className="mb-4 pb-2">Ten en cuenta que independientemente de la entidad con la que contrates para el procesamiento de pagos de Atemporal, todos los demás servicios ofrecidos por Atemporal se ofrecen a través de tu entidad local. Si cambias tu lugar de residencia, la empresa Atemporal con la que contrates se determinará por tu nuevo lugar de residencia según lo especificado anteriormente a partir de la fecha en que cambies tu lugar de residencia.</p>
          <h4 className="h4">1.3 Qué más.</h4>
          <p className="mb-4 pb-2">Si eres un Organizador que ofrece eventos con boletos pago, también te serán aplicables el Acuerdo comercial y los Requisitos de la política de reembolsos para los organizadores de Atemporal. Si eres un Organizador o Consumidor, te serán aplicables las Directrices de la comunidad de Atemporal. (Algunos de los términos en esos acuerdos están duplicados en estos Términos de servicio, pero no todos). Si eres un tercero que interactúa con nuestros Servicios no como un Organizador o un Consumidor, es posible que te sean aplicables los Términos de uso de API o la Política sobre marcas comerciales y derechos de autor. Pon atención a los términos y condiciones adicionales que se muestran con ciertos Servicios que puedas utilizar de vez en cuando, ya que también te serán aplicables. Y, al aceptar estos Términos de servicio, reconoces que has leído la Política de privacidad y la Declaración de cookies aplicable a todos los Usuarios. A veces podemos proporcionarte servicios que no se describen en estos Términos de servicio, o servicios personalizados: a menos que hayamos celebrado un acuerdo separado y firmado que sustituya expresamente estos Términos de servicio, estos Términos de servicio se aplicarán también a esos servicios.</p>
          <h4 className="h4">1.4 Qué significan los &#34;Términos de servicio&#34;.</h4>
          <p className="mb-4 pb-2">Estos Términos de servicio y los demás documentos a los que se hace referencia (incluida la Sección 1.3 anterior) incluyen los &#34;Términos&#34; de Atemporal. Estos Términos son un acuerdo legalmente vinculante entre tú y Atemporal que rige tu acceso y uso de los Servicios y establece tus derechos y responsabilidades cuando utilizas los Servicios. Al utilizar cualquiera de nuestros Servicios (incluida la navegación en un Sitio), aceptas estos Términos. Si no aceptas estos Términos, no utilices los Servicios ni accedas a ellos. Si vas a utilizar los Servicios en nombre de una entidad (como en nombre de tu empleador), aceptas los presentes Términos en nombre de dicha entidad y sus filiales, y declaras que tienes facultad para hacerlo. En tal caso, las referencias a &#34;tú&#34; y &#34;tu&#34; se referirán a dicha entidad.</p>

          <h3 className="h3">2. Servicios y rol de Atemporal</h3>
          <h4 className="h4">2.1 Lo que hacemos. </h4>
          <p className="mb-4 pb-2">Los Servicios de Atemporal ofrecen una manera rápida y sencilla para que los Organizadores creen perfiles de ponentes, perfiles de organizadores y otras páginas web relacionadas con sus eventos, promocionen estas páginas web y los eventos a los visitantes o navegadores en los Servicios o en cualquier otro lugar en línea, gestionen boletos y registros en línea o in situ, soliciten donaciones y vendan o reserven artículos promocionales o alojamientos relacionados con esos eventos a Consumidores o a Usuarios. Las descripciones de otros servicios más específicos generalmente pueden encontrarse en el Sitio de cada una de las Propiedades de Atemporal.</p>
          <h4 className="h4">2.2 Cómo encajamos.</h4>
          <p className="mb-4 pb-2">Atemporal no es el creador, organizador ni el propietario de los eventos listados en los Servicios. Por el contrario, Atemporal proporciona sus Servicios, que permiten a los Organizadores gestionar la venta de boletos y el registro y promocionar sus eventos. El Organizador es el único responsable de garantizar que cualquier página que muestre un evento en los Servicios (y el evento mismo) cumpla todas las leyes, normas y reglamentaciones locales, estatales, provinciales, nacionales y de otro tipo, y que los bienes y servicios descritos en la página del evento se entreguen como se describe y de una manera satisfactoria y precisa. El Organizador de un evento de pago selecciona el método de procesamiento de pagos para su evento como se describe más detalladamente en el Acuerdo comercial. Los Consumidores deben utilizar cualquier método de procesamiento de pagos que seleccione el Organizador. Si el Organizador selecciona un método de procesamiento de pagos que utilice un tercero para procesar los pagos, ni Atemporal ni sus socios de procesamiento de pagos procesarán la transacción, sino que transmitiremos los detalles de pago del Consumidor al proveedor de servicios de pago designado por el Organizador. Si un Organizador usa el procesamiento de pagos de Atemporal (como se define en el Acuerdo comercial), Atemporal actúa también como el agente limitado del Organizador únicamente para el fin de usar a nuestros proveedores de servicios de pago externos para cobrar pagos realizados por Consumidores en los Servicios y pasar tales pagos al Organizador.</p>

          <h3 className="h3">3. Privacidad e información del consumidor</h3>
          <p className="mb-4 pb-2">3.1  Sabemos que tu información personal es importante para ti, y también es importante para Atemporal. La información proporcionada a Atemporal por los Usuarios o recopilada por Atemporal a través de las Propiedades de Atemporal, se rige por nuestra Política de privacidad.</p>
          <p className="mb-4 pb-2">3.2  Si eres un Organizador, declaras, garantizas y aceptas que (a) cumplirás en todo momento todas las leyes, normas y reglamentaciones locales, estatales, provinciales, nacionales y de otro tipo con respecto a la información que recopiles (o recibas sobre) consumidores, y (b) cumplirás en todo momento las políticas aplicables publicadas en los Servicios con respecto a la información que recopiles de (o recibas sobre) los consumidores.</p>

          <h3 className="h3">4. Vigencia y finalización</h3>
          <p className="mb-4 pb-2">4.1 Estos Términos se te aplican tan pronto como accedas a los Servicios por cualquier medio y continúan en vigor hasta que finalicen. Puede llegar el momento en que tú o Atemporal decidan que es mejor separarse, como se describe en las Secciones 4.2 o 4.3 a continuación. Cuando eso sucede, estos Términos generalmente ya no se aplicarán. Sin embargo, como se describe en la Sección 4.4, ciertas disposiciones siempre serán aplicables tanto a ti como a Atemporal.</p>
          <p className="mb-4 pb-2">4.2 Atemporal puede rescindir tu derecho a utilizar los Servicios en cualquier momento (a) si infringes o incumples estos Términos; (b) si haces un uso incorrecto o mal uso de los Servicios, o utilizas los Servicios de una manera no prevista o permitida por Atemporal; o (c) si permitirte el acceso y uso de los Servicios infringiese cualquier ley, reglamentación y regulación local, estatal, provincial, nacional y de otro tipo, o expusiese a Atemporal a responsabilidad legal. Atemporal puede optar por dejar de ofrecer los Servicios, o cualquier porción particular del Servicio, o modificar o reemplazar cualquier aspecto del Servicio, en cualquier momento. Haremos todos los esfuerzos razonables para enviarte un aviso de nuestra cancelación de tu acceso a los Servicios, donde, a exclusivo criterio de Atemporal, no hacerlo te perjudicaría sustancialmente. Aceptas que Atemporal no será responsable ante ti o ante otra parte de cualquier finalización de tu derecho a utilizar o, de otro modo, acceder a los Servicios.</p>
          <p className="mb-4 pb-2">4.3 Salvo en la medida en que hayas acordado lo contrario mediante un acuerdo aparte por escrito entre tú y Atemporal, puedes poner fin a tu acceso a los Servicios y la aplicabilidad general de los Términos cerrando tu cuenta. Si eres un Consumidor que utiliza los Servicios sin una cuenta registrada, tu única opción para que estos Términos ya no se apliquen es dejar de acceder a los Servicios de forma indefinida. Siempre y cuando continúes accediendo a los Servicios, incluso sin una cuenta, estos Términos seguirán vigentes. Si existe un acuerdo aparte entre tú y Atemporal que rija el uso que haces de los Servicios y dicho acuerdo finaliza o vence, estos presentes Términos (sin la modificación que implique tal acuerdo) regirán el uso que hagas de los Servicios hasta tal terminación o rescisión.</p>
          <p className="mb-4 pb-2">4.4 Todas las disposiciones de estos Términos que, por su naturaleza, deban permanecer vigentes tras la finalización de estos Términos, perdurarán (incluidas, entre otras, todas las limitaciones sobre la responsabilidad, las exenciones, las obligaciones de indemnización, las exclusiones de garantías, los acuerdos de arbitraje, la elección de tribunal y foro judicial, y las licencias y protección de la propiedad intelectual).</p>

          <h3 className="h3">5. Controles de exportación y países restringidos.</h3>
          <p className="mb-4 pb-2">Como empresa global con sede en México con operaciones en otros países, Atemporal cumple ciertos controles de exportación y leyes de sanciones económicas. Todos los usuarios, independientemente de su ubicación o la ubicación del evento, deben familiarizarse con estas restricciones. Al aceptar estos Términos, declaras y garantizas lo siguiente: (a) no te encuentras en un país al que EE. UU., Reino Unido, la Unión Europea, Australia o Canadá haya embargado bienes y/o servicios del mismo tipo que los Servicios, incluidos entre otros Cuba, Irán, Corea del Norte, Siria o la región de Crimea de Ucrania; y (b) no eres una persona o entidad que sea propiedad de o esté bajo el control de, o afiliada a una persona o entidad que aparezca en (i) la lista de evasores de sanciones del extranjero, la lista del consejo legislativo palestino o la lista de nacionales especialmente designados de la U.S. Office of Foreign Assets Control (oficina de control de activos extranjeros de EE. UU.); la lista de exclusión de terroristas del U.S. Department of State (departamento de estado de EE. UU.); la lista de personas o entidades no autorizadas, o la lista no verificada del Departamento de industria y seguridad; la lista consolidada de objetivos publicada por el Departamento de Relaciones Exteriores y Comerciales de Australia; (ii) que esté sujeta a sanciones en cualquier otro país; o (iii) que esté implicada en el diseño, desarrollo o producción de vehículos aéreos no tripulados, misiles o armas nucleares, biológicas o químicas.</p>

          <h3 className="h3">6. Exoneración e indemnización.</h3>
          <p className="mb-4 pb-2">Aquí es donde aceptas cubrir a Atemporal si utilizas el Servicio de alguna manera por la que Atemporal sea objeto de un asunto legal, o deba afrontar otras reclamaciones o gastos, o según lo establecido aquí, en la medida en que lo permitan las leyes aplicables.</p>
          <h4 className="h4">6.1 Exoneración.</h4>
          <p className="mb-4 pb-2">Por el presente documento aceptas exonerar a Atemporal de todos los daños (ya sean directos, indirectos, fortuitos, consecuentes o de otro tipo), pérdidas, responsabilidades, costos y gastos de cualquier tipo y naturaleza, conocidos y desconocidos, que surjan de algún modo de disputas entre tú y terceros (incluidos otros Usuarios), o estén relacionados con estas, en lo relativo a los Servicios u otro evento indicado en los Servicios. Además, renuncias a cualquier ley o estatuto aplicable, que, en esencia, especifique lo siguiente: &#34;UNA EXONERACIÓN GENERAL NO SE EXTIENDE A LAS RECLAMACIONES QUE EL ACREEDOR DESCONOCE O NO SOSPECHA QUE EXISTAN A SU FAVOR EN EL MOMENTO DE EJECUTAR LA EXONERACIÓN, LAS CUALES, DE HABERSE CONOCIDO, AFECTARÍAN MATERIALMENTE A SU LIQUIDACIÓN CON EL DEUDOR&#34;.</p>
          <h4 className="h4">6.2 Indemnización.</h4>
          <p className="mb-4 pb-2">Aceptas defender, indemnizar y liberar de responsabilidades a Atemporal y a cada uno de sus funcionarios, directores, agentes, socios de marca compartida, licenciatarios, socios de procesamiento de pagos, otros socios y empleados respectivos de todos los daños (ya sean directos, indirectos, fortuitos, derivados o de otro tipo), pérdidas, responsabilidades, costos y gastos (incluidas, sin limitación, honorarios de contabilidad y abogados razonables) que resulten de cualquier reclamación, demanda, acción, procedimiento (ya sea ante un árbitro, tribunal, mediador u otro) o investigación realizada por cualquier tercero (cada una es una &#34;Reclamación&#34;) debida a o que surja de: (a) tu incumplimiento de estos Términos (incluidos los términos, acuerdos o políticas que se incorporen a estos Términos); (b) tu uso de los Servicios que incumplan estos Términos u otras políticas que publiquemos o facilitemos; (c) tu incumplimiento de las leyes, reglas y normativas locales, estatales, provinciales y nacionales aplicables o vulneración de los derechos de un tercero; (d) la recaudación y remisión de impuestos de Atemporal y (e) si eres un Organizador, tus eventos (incluso cuando Atemporal ofreció servicios con respecto a esos eventos), siempre que en caso de (e) esta indemnización no se aplicará en la medida en que la Reclamación surja de una negligencia o conducta indebida de Atemporal. Atemporal te notificará cualquier Reclamación de ese tipo, siempre que tus obligaciones aquí estipuladas no se vean limitadas si Atemporal no realizara la notificación o tardara en hacerlo, salvo en la medida en que te veas perjudicado desde el punto de vista material debido a dicho fallo. Además, en determinadas circunstancias Atemporal puede optar por gestionar la Reclamación por su propia cuenta, en cuyo caso aceptas cooperar con Atemporal de la manera que solicitemos.</p>

          <h3 className="h3">7. Renuncia de garantías y asunción de riesgos por tu parte</h3>
          <p className="mb-4 pb-2">Nos esforzamos por brindar los Servicios de la manera en que los necesitas, pero hay algunas cosas que es importante que comprendas y que no podemos prometer.</p>
          <p className="mb-4 pb-2">En la medida en que lo permita la ley aplicable, los Servicios se prestan tal cual y &#34;sujetos a disponibilidad&#34;. Atemporal renuncia expresamente a todas las garantías de cualquier tipo, explícitas o implícitas, incluidas, entre otras, las garantías implícitas de mercantibilidad, título, no infracción e idoneidad para un fin determinado. Por ejemplo, Atemporal no garantiza que: (a) los servicios (o cualquier parte de los Servicios) satisfagan tus requisitos o expectativas, (b) que los Servicios no se interrumpan, sean oportunos, sean seguros o no presenten errores, o (c) los resultados que se puedan obtener del uso de los servicios sean precisos o fiables.</p>
          <p className="mb-4 pb-2">Reconoces que Atemporal no garantiza ni tiene control sobre la calidad, la seguridad, la precisión o la legalidad de cualquier evento o Contenido asociado con un evento, la autenticidad o la precisión cualquier información proporcionada por los Usuarios (incluida la información personal del Consumidor compartida con Organizadores en conexión con eventos) o la capacidad de cualquier Usuario de realizar o completar realmente una transacción. Atemporal no tiene ninguna responsabilidad contigo, y por el presente documento renuncia a toda responsabilidad derivada de los actos u omisiones de terceros a los que Atemporal requiera para proporcionar los Servicios o si un Organizador decide ayudar con un evento, o que decidas contratar al utilizar los Servicios.</p>
          <p className="mb-4 pb-2">Comprendes y aceptas que algunos eventos pueden conllevar un riesgo inherente, y al participar en esos eventos, eliges asumir esos riesgos voluntariamente. Por ejemplo, algunos eventos pueden conllevar el riesgo de enfermedad, lesión corporal, discapacidad o muerte, y tú libre y voluntariamente asumes esos riesgos al elegir participar en esos eventos.</p>
          <p className="mb-4 pb-2">Los descargos de responsabilidad anteriores se aplican en la medida máxima permitida por la ley. Puedes tener otros derechos legales. Sin embargo, la duración de las garantías exigidas por ley, de haberlas, se limitará a la extensión máxima permitida por la ley.</p>

          <h3 className="h3">8. Limitación de responsabilidad</h3>
          <p className="mb-4 pb-2">8.1 En la medida permitida por las leyes aplicables, o según se establezca aquí, Atemporal y cualquier persona o entidad asociada con la prestación de los Servicios de Atemporal (por ejemplo, un afiliado, proveedor, socio estratégico o empleado) (&#34;Partes asociadas&#34;), no será responsable ante ti o un tercero de: (a) ningún daño indirecto, fortuito, especial, consecuente, punitivo o ejemplar, incluidos, entre otros, daños y perjuicios por pérdida de beneficios, buena voluntad, uso, datos, costos de oportunidad, pérdidas intangibles o el costo de los servicios sustitutivos (incluso si se ha notificado a Atemporal la posibilidad de tales daños); o (b) tu Contenido. Además, aparte de la obligación de Atemporal de pagar las Tarifas de registro de eventos en ciertas circunstancias a ciertos organizadores bajo el Acuerdo comercial, y solo de acuerdo con los términos del mismo, la responsabilidad agregada máxima de Atemporal o las Partes asociadas se limita a lo siguiente:</p>
          <p className="mb-4 pb-2">(i) para Organizadores de eventos con boleto pago, y sujeto a los términos del Acuerdo comercial, las tarifas (neto de las tarifas de procesamiento de pagos de Atemporal) que pagaste en el periodo de tres (3) meses inmediatamente anterior a las circunstancias que dieron lugar a tu reclamación; y</p>
          <p className="mb-4 pb-2">(ii) para Organizadores de eventos solo con boletos gratuitos, los Consumidores u otros Usuarios, (1) el importe total de todos los boletos o registros que compraste o realizaste a través de los Servicios en el periodo de tres (3) meses inmediatamente anterior a las circunstancias que dieron lugar a tu reclamación; o (2) si no realizaste tales compras, cien dólares estadounidenses (100 $ US).</p>
          <p className="mb-4 pb-2">8.2 Nada en estos Términos tiene la intención de excluir o limitar ninguna condición, garantía, derecho o responsabilidad que no esté legalmente excluida o limitada. Algunas jurisdicciones no permiten la exclusión de ciertas garantías o condiciones ni la limitación o exclusión de responsabilidades por pérdidas o daños originados por actos dolosos, negligencia, incumplimiento de contrato o incumplimiento de las condiciones implícitas, o bien por daños fortuitos o derivados. En consecuencia, únicamente se te aplicarán aquellas responsabilidades y otras limitaciones que sean legítimas en tu jurisdicción (si las hubiera), y nuestra responsabilidad se limitará al máximo permitido por la ley.</p>

          <h3 className="h3">9. IMPORTANTE: Disposición vinculante sobre arbitraje y renuncia a demandas de grupo.</h3>
          <p className="mb-4 pb-2">LEE DETENIDAMENTE ESTA SECCIÓN, YA QUE AFECTA A TUS DERECHOS. TODAS LAS DISPUTAS O RECLAMACIONES EN VIRTUD DE LOS PRESENTES TÉRMINOS O RELACIONADAS CON LOS SERVICIOS SE RESOLVERÁN MEDIANTE ARBITRAJE VINCULANTE O PROCESOS MONITORIOS (EN LA MEDIDA EN QUE LA RECLAMACIÓN LO PERMITA) Y SE REALIZARÁN ÚNICAMENTE A TÍTULO INDIVIDUAL; ACEPTAS QUE NO SE PERMITEN DEMANDAS DE ARBITRAJE Y CIVILES DE GRUPO, ACUMULADAS O REPRESENTATIVAS Y QUE CADA PARTE RENUNCIA A CUALQUIER DERECHO PARA LLEVAR A CABO TALES ACCIONES.</p>
          <p className="mb-4 pb-2">Las partes entienden que, en ausencia de esta disposición obligatoria, tendrían el derecho de demandar ante un tribunal y tener un juicio por jurado. Además, entienden que, en algunos casos, los costos del arbitraje podrían exceder los costos del litigio y el derecho de descubrimiento puede ser más limitado en el arbitraje que en los tribunales.</p>
          <p className="mb-4 pb-2">(a) Primero ponte en contacto con nosotros. Si tienes preguntas o dudas sobre los Servicios, contáctanos en primer lugar. Nuestro equipo de atención al cliente intentará responder a tu pregunta o resolver tu duda.</p>
          <p className="mb-4 pb-2">(b) Acuerdo de arbitraje. En el improbable caso de que nuestro equipo de atención al cliente no pueda resolver tus problemas, las partes (tú y nosotros) acordamos por el presente documento resolver todas las disputas o reclamaciones relacionadas con estos Términos, con respecto a los Servicios, o relacionadas con nuestra relación a través de Arbitraje vinculante o procesos monitorios (en la medida en que la reclamación lo permita) en lugar de en tribunales de jurisdicción general y solo de forma individual. En ningún caso podemos, ni nosotros ni tú, tratar de resolver una disputa con el otro como parte de un supuesto procedimiento de clase, consolidado o representativo. El arbitraje vinculante permite pocos recursos ante tribunales superiores. Únicamente el árbitro designado en virtud de esta Sección, y no tribunales u organismos federales, estatales o locales, tendrán competencias para resolver disputas o reclamaciones relacionadas con esta Sección, incluido, entre otros, el alcance, la aplicabilidad y la arbitrabilidad de estos Términos. Esta disposición sobre arbitraje continuará tras la extinción de los presentes Términos. Los presentes Términos demuestran una transacción en comercio interestatal, y la interpretación y ejecución de esta Sección 9 se rigen por la ley federal de arbitraje (Federal Arbitration Act), sin perjuicio de la ley elegida establecida en la Sección 9(h) a continuación.</p>
          <p className="mb-4 pb-2">(c) Ámbito del acuerdo. El presente acuerdo de arbitraje debe interpretarse en términos generales en cuanto a disputas legales entre tú y nosotros. Incluye, de forma enunciativa mas no limitativa: (i) todas las reclamaciones que surjan de cualquier aspecto de la relación entre nosotros o estén relacionadas con cualquier aspecto de esta, independientemente de si se basan en contrato, acto ilícito, ley, fraude, falsedad o cualquier otra teoría jurídica; (ii) todas las reclamaciones que hayan surgido antes del presente acuerdo o de cualquier acuerdo anterior (incluidas, entre otras, las reclamaciones relacionadas con la publicidad); y (iii) todas las reclamaciones que puedan surgir tras la finalización de estos Términos o uso de los Servicios por tu parte.</p>
          <p className="mb-4 pb-2">(d) Excepciones. Sin perjuicio de lo dispuesto en el presente Acuerdo de arbitraje, cualquiera de las partes puede (i) interponer una demanda de forma individual para procesos monitorios (en la medida en que la reclamación aplicable lo permita), o (ii) iniciar acciones ejecutivas, determinaciones de validez o reclamaciones derivadas o relacionadas con el robo, la piratería o el uso no autorizado de propiedad intelectual en un tribunal estatal o federal de la Oficina de Patentes o Marcas de los Estados Unidos para proteger sus derechos de propiedad intelectual (&#34;Derechos de propiedad intelectual&#34; significa patentes, derechos de autor, derechos morales, marcas comerciales y secretos comerciales, pero no derechos de privacidad o publicidad). Además, la parte de cualquier disputa o queja relacionada con nuestra participación en las Estructuras de Escudo de Privacidad EE. UU.-UE o EE. UU.-Suiza está sujeta a la sección de Resolución de disputas de nuestra Política de privacidad antes de estar sujeta a esta sección.</p>
          <p className="mb-4 pb-2">(e) Sin demandas de grupo. Atemporal Y TÚ ACUERDAN QUE ÚNICAMENTE PUEDEN PRESENTAR DEMANDAS CONTRA LA OTRA PARTE A TÍTULO INDIVIDUAL, Y NO COMO DEMANDANTE O MIEMBRO DE UN GRUPO EN PROCEDIMIENTOS DE GRUPO, ACUMULADOS O REPRESENTATIVOS. EL ÁRBITRO NO PUEDE UNIR MÁS DE UNA RECLAMACIÓN DE ALGUNA DE LAS PARTES, NO PUEDE PRESIDIR PROCEDIMIENTOS DE GRUPO, ACUMULADOS O REPRESENTATIVOS Y ÚNICAMENTE PUEDE OFRECER REPARACIONES A FAVOR DE LA PARTE INDIVIDUAL QUE SOLICITA LA REPARACIÓN Y ÚNICAMENTE EN LA MEDIDA NECESARIA PARA OFRECER LA REPARACIÓN POR LA RECLAMACIÓN INDIVIDUAL DE DICHA PARTE.</p>
          <p className="mb-4 pb-2">(f) Notificación de disputa. Las partes que soliciten arbitraje deberán enviar previamente a la otra parte una Notificación de disputa (“Notificación”) por escrito. La Notificación a Atemporal deberá enviarse a la dirección siguiente (&#34;Dirección de notificación&#34;) y debe enviarse por correo certificado: Atemporal, Dirección Atemporal La Notificación que se te envíe deberá enviarse mediante correo postal certificado a una dirección de correo postal, de residencia o de pago que esté registrada actualmente en Atemporal. Si Atemporal carece del registro de una dirección física, la notificación podrá enviarse a la dirección de correo electrónico de tu cuenta de Atemporal. La Notificación debe (i) describir la naturaleza y el fundamento de la reclamación o disputa, y (ii) establecer la reparación específica que se solicita. Si Atemporal y tú no llegan a un acuerdo para resolver la reclamación en un plazo de sesenta (60) días naturales a partir de la recepción de la Notificación, Atemporal o tú podrán iniciar un procedimiento de arbitraje.</p>
          <p className="mb-4 pb-2">(g) Procedimientos de arbitraje. El arbitraje se regirá por las (Normas de arbitraje comercial &#8594; https://www.adr.org/Rules), o, si las acciones que dan lugar a la disputa o reclamación están relacionadas con tu uso personal o doméstico de los Servicios, en lugar de un uso comercial, por las Normas de arbitraje para consumidores (en todos los casos, las &#34;Normas de la AAA&#34;) de la Asociación americana de arbitraje (&#34;AAA&#34;, de American Arbitration Association), según su modificación en esta Sección 9, y será administrado por la AAA y resuelto por un único árbitro. (Las Normas de la AAA también están disponibles llamando a la AAA al 1-800-778-7879). El árbitro decidirá sobre todos los asuntos, incluidos, de forma enunciativa mas no limitativa, los asuntos relacionados con el ámbito, la capacidad de ejecución y la arbitrabilidad de esta Sección 9.</p>
          <p className="mb-4 pb-2">(h) Ubicación de los procedimientos de arbitraje. Si eres un Consumidor, las audiencias de arbitraje se llevarán a cabo (a tu elección) ya sea en el condado de tu residencia o por teléfono, salvo que seas un Consumidor cuya residencia se encuentre fuera de los Estados Unidos, la audiencia tendrá lugar ya sea en San Francisco, California, o por teléfono o videoconferencia, a tu elección y según lo permitan las Normas de la AAA. Si eres un negocio (es decir, tu uso de los Servicios fue para uso comercial), salvo que Atemporal y tú acuerden lo contrario, todos los juicios de arbitraje tendrán lugar en una ubicación razonablemente conveniente para ambas partes en el territorio de los Estados Unidos, y se tendrá en cuenta la capacidad de viajar y otras circunstancias relevantes. Si las partes no alcanzan un acuerdo sobre la ubicación, la AAA determinará la ubicación. Si tu reclamación es de un máximo de diez mil dólares (10 000 USD), aceptamos que elijas si deseas que el arbitraje se realice exclusivamente en función de los documentos entregados al árbitro, mediante un juicio por teléfono o mediante un juicio en persona tal y como establecen las Normas de la AAA. Si tu reclamación supera los diez mil dólares (10 000 USD), las normas de la AAA determinarán el derecho a juicio. Independientemente de la manera en que se lleve a cabo el arbitraje, el árbitro emitirá un fallo razonado por escrito donde explique las conclusiones y los hallazgos clave en los que se basa el fallo arbitral. Todas las decisiones tomadas por el árbitro serán firmes y vinculantes, y se podrá dictar sentencia sobre el fallo arbitral en cualquier tribunal con jurisdicción para ello.</p>
          <p className="mb-4 pb-2">(i) Costos del arbitraje; Tarifas legales. </p>
          <p className="mb-4 pb-2">i. Pago de costos y gastos. El pago de todos los costos y gastos de tramitación, administración y del árbitro impuestos por la AAA se regirán por las Normas de la AAA, y si iniciaras un proceso de arbitraje contra Atemporal y el valor de la indemnización solicitada es, como máximo, de diez mil dólares (10 000 USD), Atemporal adelantaría todos los costos y gastos de tramitación, administración y del árbitro impuestos por la AAA (sujetos a reembolso, tal y como se establece a continuación). Además, si se cumplen las circunstancias expuestas anteriormente y tu reclamación surge de tu uso de los Servicios como Consumidor, pero el valor de la indemnización solicitada es de más de diez mil dólares (10 000  USD) y demuestras al árbitro que dichos costos y gastos serían mucho mayores que los que conllevaría un procedimiento judicial, Atemporal abonará el importe de los costos y gastos. En caso de que el árbitro determine que alguna de tus reclamaciones es frívola de acuerdo con la Norma federal de procedimientos civiles 11, aceptas reembolsar a Atemporal todos los costos y gastos abonados por Atemporal y que habrías tenido que pagar en virtud de las Normas de la AAA.</p>
          <p className="mb-4 pb-2">ii. Pago de tarifas legales. Como en cualquier procedimiento judicial, cada parte correrá con los honorarios y gastos de sus propios abogados para cualquier arbitraje. Si se considera que una de las partes es la clara ganadora del arbitraje, el árbitro abonará a dicha parte ganadora, a petición de esta, los honorarios y gastos razonables de abogados en los que se incurrió a causa del arbitraje, siempre y cuando, en la medida en que la disputa o reclamación esté relacionada con tu uso personal o doméstico de los Servicios (en lugar de uso comercial), Atemporal no intente recuperar los honorarios y gastos de sus abogados en el arbitraje iniciado por ti. El árbitro puede dictar fallos y resolver disputas sobre el reembolso de los honorarios y gastos de abogados a petición de cualquiera de las partes en un plazo de catorce (14) días a partir del momento en que el árbitro dicta su fallo visto el fondo de la cuestión.</p>
          <p className="mb-4 pb-2">(j) Cambios futuros. Sin perjuicio de lo dispuesto en sentido contrario en los presentes Términos, Atemporal y tú acuerdan que, si Atemporal realiza algún cambio en el futuro en esta disposición de arbitraje (que no sea un cambio en la Dirección de notificación), se te enviará una notificación de dicho cambio, que podrás rechazar enviándonos una notificación por escrito en un plazo de treinta (30) días naturales a partir de la fecha del cambio a la Dirección de notificación facilitada anteriormente. Si rechazas algún cambio futuro, aceptas que arbitrarás cualquier disputa entre nosotros de acuerdo con esta disposición sin la modificación de dicho cambio rechazado.</p>
          <p className="mb-4 pb-2">(k) Divisibilidad especial. En el caso de que alguna disposición de esta Sección 9 se considerara no válida o que no se pudiera ejecutar en relación con alguna disputa o reclamación, la totalidad de esta Sección 9 será nula y no tendrá valor en relación con dicha disputa o reclamación, y se aplicará la Sección 23 en lugar de esta Sección 9.</p>
          <p className="mb-4 pb-2">(l) Opción de exclusión. Tienes derecho a optar por excluirte y no estar sujeto a las disposiciones de arbitraje o de demandas de grupo estipuladas anteriormente mediante el envío de un aviso por escrito (desde la dirección de correo electrónico que asociamos contigo como Usuario) de tu decisión de quedar excluido a ebmail(legal@Atemporal.com &#8594; mailto:legal@Atemporal.com?subject=ARBITRATION AND CLASS ACTION WAIVER OPT-OUT&body=Añade aquí tu solicitud.), con la línea de asunto &#34;ARBITRATION AND CLASS ACTION WAIVER OPT-OUT&#34;. El aviso debe enviarse en el plazo de los treinta (30) días de tu primer uso de los Servicios o tu aceptación de estos Términos (lo que sea posterior); de lo contrario, estarás obligado a arbitrar disputas de acuerdo con los términos de esos párrafos. Ten en cuenta que si no aceptas estas disposiciones de arbitraje, Atemporal tampoco estará obligado por ellas.</p>

          <h3 className="h3">10. Licencia para los servicios de Atemporal</h3>
          <p className="mb-4 pb-2">10.1 Licencia para los Servicios. Te otorgamos un derecho limitado, no exclusivo, intransferible, no sublicenciable (excepto para los Subusuarios registrados a través de los Servicios), revocable de utilizar nuestros Servicios únicamente para (a) explorar los Servicios y buscar, ver y registrar o comprar boletos o registros para un evento enumerado en los Servicios; y/o (b) crear registro de eventos, perfil de organizador y otras páginas web para promocionar, comercializar, gestionar, seguir y recaudar ingresos de ventas para un evento. Tu uso de los Servicios debe cumplir estos Términos y todas las leyes, reglas y normativas locales, estatales, provinciales y nacionales. Además, al utilizar cualquier función de búsqueda o herramientas de rellenado automático de direcciones, quedas obligado por las Condiciones del Servicio Adicionales de Google Maps o Google Earth (incluida la Política de Privacidad de Google).</p>
          <p className="mb-4 pb-2">10.2 Restricciones en tu licencia. Sin limitaciones sobre otras restricciones, limitaciones y prohibiciones que imponemos (en estos Términos o en otro lugar), aceptas que ni directa ni indirectamente (a) copiarás, modificarás, reproducirás, traducirás, localizarás, portarás ni crearás derivados de ninguna parte de los Servicios; (b) realizarás ingeniería inversa, desensamblarás, descompilarás ni intentarás descubrir el código fuente o la estructura, secuencia y organización de la totalidad o parte de los Servicios; (c) alquilarás, arrendarás, revenderás, distribuirás, utilizarás los Servicios para otros fines comerciales no contemplados o explotarás los Servicios de cualquier manera no autorizada; (d) eliminarás o alterarás los avisos de propiedad de los Servicios; o (e) participarás en cualquier actividad que interfiera o interrumpa los Servicios.</p>
          <p className="mb-4 pb-2">10.3 Nuestra propiedad intelectual y derechos de autor. Aceptas que todo el Contenido del sitio puede estar protegido por derechos de autor, marcas comerciales, marcas de servicio, secretos comerciales u otra propiedad intelectual y otros derechos y leyes de propiedad. Atemporal puede poseer el Contenido del sitio o puede poner a disposición parte del Contenido del sitio mediante acuerdos con terceros. El Contenido del sitio incluido o entregado a través de los Servicios es propiedad exclusiva de Atemporal y está protegido por leyes de copyright. Aceptas que solo podrás utilizar el Contenido del sitio para los fines permitidos por estos Términos y por cualquier ley, regla o normativa local, estatal, provincial, nacional o de otro tipo aplicable. Quedan reservados todos los derechos no concedidos aquí expresamente.</p>
          <p className="mb-4 pb-2">10.4 Marcas comerciales. Las marcas comerciales, las marcas de servicio y los logotipos de Atemporal (las &#34;Marcas comerciales de Atemporal&#34;) utilizados y mostrados para lo relacionado con los Servicios son marcas de servicio o marcas comerciales registradas o no registradas de Atemporal. Otros nombres de empresas, productos y servicios utilizados en relación con los Servicios pueden ser marcas comerciales o de servicio propiedad de terceros (las &#34;Marcas comerciales de terceros&#34; y, junto con las Marcas comerciales de Atemporal, las &#34;Marcas comerciales&#34;). La oferta de los Servicios no se debe interpretar como la concesión, por implicación, impedimento legal o de otro modo, de licencia o derecho alguno para utilizar cualquier Marca comercial mostrada en relación con los Servicios sin el consentimiento previo de Atemporal específico para cada uso. Las Marcas comerciales no pueden utilizarse para desacreditar a Atemporal, a un tercero o a los productos o servicios de Atemporal o dicho tercero, ni de cualquier forma que pueda dañar la buena fe de las Marcas comerciales. El uso de una Marca comercial como parte de un enlace a un sitio o desde un sitio cualquiera está prohibido, a menos que Atemporal apruebe el establecimiento de dicho enlace mediante consentimiento previo por escrito de forma específica para cada enlace. Toda la buena fe generada a partir del uso de cualquier Marca comercial de Atemporal redundará en beneficio de Atemporal. Existe una serie de patentes emitidas y patentes pendientes que se aplican a los Servicios. El Contenido del sitio también puede estar protegido por derechos de autor propiedad de Atemporal y/o terceros. Ten en cuenta que si copias partes de los Servicios, estarás violando sus derechos de patente y de autor.</p>
          <p className="mb-4 pb-2">10.5 Uso de subdominios. Atemporal puede proporcionarte el derecho a utilizar un subdominio en el Sitio (por ejemplo, [prefijo del subdominio].Atemporal.com.mx) para un evento determinado. Todos los subdominios son propiedad exclusiva de Atemporal, y Atemporal se reserva el derecho a determinar el aspecto, el diseño, la funcionalidad o cualquier otro elemento de dichos subdominios. En caso de que Atemporal te proporcionara un subdominio, tu derecho a utilizar dicho subdominio continuará siempre y cuando tu evento siga dando lugar a ventas activas en los Servicios, y solo si cumples con los Términos, incluidos, sin limitación, estos Términos de servicio. Si Atemporal cancela tu derecho a utilizar un subdominio por cualquier otro motivo, te proporcionará un nuevo subdominio.</p>

          <h3 className="h3">11. Licencias y permisos que los organizadores deben obtener</h3>
          <p className="mb-4 pb-2">Si eres un Organizador, sin limitar la generalidad de las representaciones o garantías proporcionadas en otras partes de estos Términos de servicio, declaras y garantizas que:</p>
          <p className="mb-4 pb-2">(a) Tú y tus afiliados obtendrán, antes del inicio de la venta de boletos, todas las licencias, permisos y autorizaciones (individualmente y colectivamente, &#34;Registro&#34;) con respecto a los eventos que tú o tus afiliados organicen en los Servicios. El Registro incluye pero no se limita a permisos de operación de propiedad y permisos de jefe de bomberos;</p>
          <p className="mb-4 pb-2">(b) Tú y tus afiliados cumplirán y se asegurarán de que los lugares para cada evento organizado por ti o tus afiliados en los Servicios cumplan todas las leyes, regulaciones, normas y ordenanzas aplicables;</p>
          <p className="mb-4 pb-2">(c ) Solo solicitarás que Atemporal ofrezca boletos para un evento después de haber obtenido Registros específicos para dicho evento, incluidas, entre otras, la autorización del evento por parte del estado, condado, municipio u otra autoridad local, autorizaciones de ingeniería de tráfico, informes de inspección del departamento de bomberos, autorización para recibir menores (si corresponde), autorización sanitaria (si corresponde) y cualquier otra posible autorización aplicable; y (d) tú y tus afiliados mantendrán en vigencia durante el plazo de acceso al Servicio el Registro aplicable para que el organizador promocione, produzca, auspicie y venda boletos para todos los eventos que tú o tus afiliados organicen en los Servicios.</p>
          <p className="mb-4 pb-2">(d) Sin limitar la generalidad de ninguna publicación provista bajo estos Términos de servicio, como un incentivo material para que Atemporal te permita acceder y utilizar los Servicios, acuerdas liberar a Atemporal, sus afiliados y subsidiarios, y cada una de sus respectivas casas matrices, subsidiarias, funcionarios, afiliados, representantes, accionistas, contratistas, directores, agentes, socios y empleados de todos los daños (ya sean directos, indirectos, fortuitos, derivados o de otro tipo), pérdidas, responsabilidades, costos y gastos de todo tipo y naturaleza, incluidos, entre otros, los honorarios de abogados, conocidos y desconocidos, que surjan o estén relacionados con el Registro tuyo o de tus afiliados, la falta de obtención o mantenimiento de cualquier Registro, o cualquier error en la obtención o mantenimiento de cualquier Registro.</p>
          <p className="mb-4 pb-2">(e) Sin limitar tus obligaciones de indemnización en otros términos bajo estos Términos de servicio, aceptas defender, indemnizar y liberar de responsabilidades a Atemporal y a cada uno de sus ejecutivos, directores, agentes, socios de marca compartida, licenciatarios, socios de procesamiento de pagos y demás socios y empleados respectivos de todos los daños (ya sean directos, indirectos, fortuitos, derivados o de otro tipo), pérdidas, responsabilidades, costos y gastos (incluidas, sin limitación, los honorarios razonables en contabilidad y abogados) que resulten de cualquier reclamación debida a o que surja de tu Registro o el de tus afiliados, cualquier fallo en la obtención o mantenimiento de cualquier Registro, o cualquier error en la obtención o mantenimiento de cualquier Registro. Aceptas proporcionar evidencia de Registro e información relacionada antes de ofrecer boletos o registros de eventos en el Sitio y puntualmente a solicitud razonable de Atemporal ocasionalmente.</p>

          <h3 className="h3">12. Tus derechos a presentar una notificación de eliminación de derechos de autor</h3>
          <p className="mb-4 pb-2">Si eres un propietario de derechos de autor o un agente de un propietario de derechos de autor y crees que cualquier contenido en los Sitios infringe tus derechos de autor, puedes enviar una notificación de conformidad con la Ley de derechos de autor para el milenio digital (&#34;DMCA&#34;) siguiendo las instrucciones que proporcionamos en la Política sobre marcas comerciales y derechos de autor de Atemporal.</p>

          <h3 className="h3">13. Se prohíbe el raspado o el uso comercial del contenido del sitio</h3>
          <p className="mb-4 pb-2">El Contenido del sitio no está destinado a uso comercial por tu parte. No tienes derecho a utilizar, y aceptas no utilizar, ningún Contenido del sitio para tus propios fines comerciales. No tienes derecho a hacerlo y aceptas no raspar, arrastrar o utilizar ningún medio automático para extraer datos de los Sitios.</p>

          <h3 className="h3">14. Tarifas y reembolsos.</h3>
          <p className="mb-4 pb-2">14.1 Tarifas que cobramos. La creación de una cuenta, la publicación de eventos y el acceso a los Servicios son gratuitos. Sin embargo, cobramos tarifas cuando vendes o compras boletos pago o registros. Estas tarifas pueden variar si existen acuerdos individuales entre Atemporal y algunos Organizadores. Los Organizadores deciden en última instancia si estas tarifas deben cobrarse a los Consumidores y mostrarse como &#34;Tarifas&#34; en la página del evento aplicable o cubrirse en el precio del boleto o el registro, en cuyo caso el Organizador utiliza los ingresos brutos obtenidos de los boletos y registros para pagarlas. Las tarifas que deben pagar los Consumidores pueden incorporar otros cargos, que pueden incluir, entre otros, cargos de instalaciones, derechos de autor, impuestos, tarifas de procesamiento y tarifas de ejecución. Por lo tanto, las tarifas que abonan los Consumidores por un evento no son necesariamente las mismas que cobra Atemporal al Organizador correspondiente o las tarifas estándar descritas en los Servicios a los Organizadores. Además, algunas tarifas sirven para sufragar determinados costos en los que incurre Atemporal y que en algunos casos pueden incluir un elemento de beneficio y en otros un elemento de pérdida. Atemporal no controla (y por lo tanto no publica) las tarifas recaudadas por tu banco y/o compañía de tarjeta de crédito, incluidas las tarifas por comprar boletos y registros en monedas extranjeras o de personas extranjeras. Asegúrate de consultar con tu banco o compañía de tarjeta de crédito antes de iniciar una transacción para conocer todas las tarifas, los recargos de tarjeta de crédito y las tarifas de conversión aplicables.</p>
          <p className="mb-4 pb-2">14.2 Cambios de boletos. Si deseas cambiar boletos a un evento que compraste en Atemporal, en algunos casos Atemporal podrá hacerlo por ti. En todos los demás casos, ponte en contacto con el Organizador del evento para organizar el cambio de boletos. Si no puedes contactar con el Organizador, o si el Organizador no puede organizar un cambio de boletos, contáctanos.</p>
          <p className="mb-4 pb-2">14.3 Reembolsos. Puesto que todas las transacciones se realizan entre un Organizador y sus respectivos asistentes, Atemporal pide a todos los Consumidores que se pongan en contacto con el Organizador del evento aplicable para solicitar reembolsos.</p>
          <p className="mb-4 pb-2">(a) Si eres un Consumidor, reconoces que si recibieras un reembolso por tu boleto, descartarás cualquier boleto que nosotros o cualquier Organizador haya entregado, y no lo utilizarás (ni copia alguna) para asistir al evento. La infracción de lo anterior constituye fraude. Reconoces que siempre se debe seguir el procedimiento aplicable para verificar la validez del boleto. Atemporal no será responsable bajo ninguna circunstancia de los costos derivados del incumplimiento por parte de los Organizadores de los procedimientos aplicables que deban implementar los Organizadores para verificar la validez de los boletos. Atemporal no será responsable bajo ninguna circunstancia de los costos y/o daños asociados con los boletos surgidos de situaciones con fraude y/o por daños asociados con la compra del boleto a través de medios no oficiales, tales como terceros.</p>
          <p className="mb-4 pb-2">(b) Si eres un Organizador, reconoces que siempre se debe seguir el procedimiento aplicable para verificar la validez del boleto. Atemporal no será responsable bajo ninguna circunstancia de los costos derivados del incumplimiento por parte de los Organizadores de los procedimientos aplicables que deban implementar los Organizadores para verificar la validez de los boletos. Atemporal no será responsable bajo ninguna circunstancia de los costos y/o daños asociados con los boletos surgidos de situaciones con fraude y/o por daños asociados con la compra del boleto a través de medios no oficiales, tales como terceros.</p>

          <h3 className="h3">15. Tu cuenta con Atemporal</h3>
          <ul className="mb-4 pb-2 ps-4">
            <li className="mb-1">Debes tener al menos 18 años de edad, o la mayoría de edad legal del lugar donde residas, para utilizar los Servicios. Si tienes 13 años o más, solo puedes utilizar los Servicios bajo la supervisión de un padre o tutor legal que administre tu uso de la cuenta y/o la cuenta misma. Sin embargo, si tienes menos de 13 años, no nos proporciones ninguna información sobre ti.</li>
            <li className="mb-1">Aceptas proporcionar información verdadera, precisa, actual y completa sobre ti, o si estás utilizando los Servicios en nombre de una entidad, la entidad (los &#34;Datos de registro&#34;). También aceptas actualizar estos Datos de registro si cambian.</li>
            <li className="mb-1">Si hay una disputa entre dos o más personas o entidades con respecto a la propiedad de la cuenta, Atemporal será el único árbitro de esa disputa y la decisión de Atemporal (que puede incluir la terminación o suspensión de la cuenta) será definitiva y vinculante para esas partes.</li>
            <li className="mb-1">Si estás utilizando los Servicios en nombre de una empresa u otra entidad, declaras y garantizas que tienes la autoridad para vincular legalmente a esa entidad y otorgarle a Atemporal todos los permisos y licencias provistos en estos Términos.</li>
            <li className="mb-1">Podemos proporcionarte la capacidad de implementar ciertos permisos dentro de tu cuenta a terceros, incluidos los &#34;subusuarios&#34;, las &#34;subcuentas&#34; u otros usuarios de cuentas con credenciales. Si lo hacemos, aceptas que eres el único responsable de todas las actividades que ocurran en tu cuenta (incluidas las acciones de los subusuarios), por lo que debes mantener la confidencialidad de tu contraseña y los detalles de tu cuenta. Asimismo, aceptas que todas las reglas aplicables a tu cuenta se aplicarán a todos los terceros a los que concedas acceso a tu cuenta.</li>
            <li className="mb-1">Aceptas notificar inmediatamente a Atemporal de cualquier uso no autorizado de tu contraseña o cuenta o de cualquier otra infracción de seguridad. Eres responsable de (y te haremos responsable) por cualquier actividad que ocurra en tu cuenta.</li>
            <li className="mb-1">Aceptas no utilizar nuestros servicios para recopilar información personal confidencial, como información médica (incluida &#34;información médica protegida&#34; como se describe en la sección 160.103 del Código de Regulaciones Federales 45), números de la seguridad social, información financiera, números de tarjetas de pago, números de licencia de conducir y números de pasaporte, a menos que se permita lo contrario en estos Términos o Atemporal consienta dicha recopilación por escrito.</li>
          </ul>

          <h3 className="h3">16. Nuestras directrices de la comunidad</h3>
          <p className="mb-4 pb-2">Te comprometes a respetar las Directrices de la comunidad de Atemporal siempre que accedas o utilices nuestros Servicios. Léelas detenidamente, ya que afectan a los tipos de contenido y la conducta permitidos en los Servicios de Atemporal.</p>

          <h3 className="h3">17. Tu contenido.</h3>
          <p className="mb-4 pb-2">17.1 Licencia. Atemporal no reclama en ningún modo Tu contenido. Sin embargo, eres el único responsable de Tu contenido. Por el presente documento concedes a Atemporal un derecho y una licencia no exclusivos, mundiales, perpetuos, irrevocables, sin derechos de autor, transferibles, sublicenciables para acceder a, utilizar, reproducir, transmitir, adaptar, modificar, ejecutar, mostrar, distribuir, traducir, publicar y crear obras derivadas basadas en Tu contenido, en su totalidad o en parte, en cualquier medio, con el fin de hacer funcionar los Servicios (incluidos los servicios promocionales y de marketing de Atemporal, que pueden incluir sin limitación, la promoción de tu evento en un sitio de un tercero), y por el presente documento renuncias a cualquier derecho moral a utilizar el nombre proporcionado con Tu contenido. Sin perjuicio de lo anterior, Atemporal no reclama, ni tú transfieres, ningún derecho de propiedad relacionado con Tu contenido, y ninguna parte de estos Términos de servicio restringe de modo alguno los derechos que puedas tener para utilizar y explotar Tu contenido fuera de los Servicios.</p>
          <p className="mb-4 pb-2">17.2 Tus representaciones sobre Tu contenido. Declaras y garantizas que posees todos los derechos, poderes y autoridad necesarios para conceder la anterior licencia y que todo Tu contenido (a) no infringe, incumple, malversa o entra, de cualquier otro modo, en conflicto con los derechos de terceros; (b) cumple todas las leyes, reglas y normativas locales, estatales, provinciales, nacionales y de otro tipo aplicables; y (c) no infringe estos Términos.</p>
          <p className="mb-4 pb-2">17.3 Reglas adicionales sobre Tu contenido. Tu contenido debe ser exacto y veraz. Atemporal se reserva el derecho a eliminar cualquier parte de Tu contenido de los Servicios si Atemporal cree, a su sola discreción, que no cumple con estos Términos, nuestras Directrices de la comunidad o por cualquier otro motivo. Atemporal puede utilizar tu nombre y logotipo (tanto si has hecho que estén disponibles a través de los Servicios como si no) con el propósito de identificarte como un cliente actual o pasado de Atemporal tanto en los Servicios como en materiales de marketing, publicitarios y promocionales. Del mismo modo podemos conservar Tu contenido y la información de tu cuenta, así como revelar Tu contenido y la información de tu cuenta si así lo requiere la ley o en la creencia de buena fe de que la preservación o revelación sean razonablemente necesarias para: (a) cumplir los procesos legales; (b) responder a las quejas que reclamen que cualquier parte de Tu contenido infringe los derechos de terceros; (c) aplicar o administrar los Términos de servicio, incluidos, sin limitación, estos Términos de servicio; y/o (d) proteger los derechos, la propiedad y/o la seguridad personal de Atemporal, sus usuarios y/o el público, incluida la prevención de fraudes. Comprendes que el procesamiento técnico y la transmisión de los Servicios, incluido Tu contenido, puede implicar transmisiones por diversas redes; y/o cambios para ajustarse o adaptarse a requisitos técnicos de conexión de redes o dispositivos.</p>

          <h3 className="h3">18. Reglas para el uso de herramientas de correo electrónico</h3>
          <p className="mb-4 pb-2">18.1 Es posible que Atemporal ponga a tu disposición funciones y herramientas que te permitan contactar con tus Consumidores, otros usuarios de los Servicios o terceros por correo electrónico (las “Herramientas de correo electrónico”). Si utilizas las Herramientas de correo electrónico, declaras y aceptas que:</p>
          <p className="mb-4 pb-2">(a) tienes el derecho y la autoridad de enviar correos electrónicos a las direcciones en tu lista de destinatarios y dichas direcciones se recopilaron de acuerdo con las regulaciones de marketing por correo electrónico en el país de residencia del destinatario;</p>
          <p className="mb-4 pb-2">(b) tus correos electrónicos no se envían en violación de ninguna política de privacidad bajo la cual se recopilaron los correos electrónicos del destinatario;</p>
          <p className="mb-4 pb-2">(c ) utilizarás las Herramientas de correo electrónico de acuerdo con todas las leyes, normas y reglamentaciones locales, estatales, provinciales, nacionales y de otro tipo, incluidas las relacionadas con el correo no deseado y el correo electrónico, y entre ellas, la ley CAN-SPAM de EE. UU. Canadian CASL, y la directiva RGPD y de privacidad electrónica de la UE;</p>
          <p className="mb-4 pb-2">(d) solo utilizarás las Herramientas de correo electrónico para anunciar, promocionar y/o gestionar un evento de buena fe publicado en los Servicios;</p>
          <p className="mb-4 pb-2">(e) tu uso de las Herramientas de correo electrónico y el contenido de tus mensajes de correo electrónico cumplen estos Términos;</p>
          <p className="mb-4 pb-2">(f) no utilizarás títulos ni líneas de asunto falsos o engañosos en los correos electrónicos enviados mediante las Herramientas de correo electrónico;</p>
          <p className="mb-4 pb-2">(g) responderás de inmediato y de acuerdo con las instrucciones a cualquier Consumidor que te envíe Atemporal solicitando que modifiques las preferencias de correo electrónico de dicho Consumidor;</p>
          <p className="mb-4 pb-2">(h) proporcionarás un enlace de cancelación de suscripción accesible e incondicional para incluir en cada correo electrónico cuando se requiera, y no enviarás ningún correo electrónico a ningún destinatario que se haya dado de baja de tu lista de correo.</p>
          <p className="mb-4 pb-2">18.2 Si infringes cualquiera de estas reglas de Herramientas de correo electrónico o si tu uso de las Herramientas de correo electrónico tiene como resultado rebotes, reclamaciones o solicitudes de anulación de suscripción por encima de los estándares del sector o si tus correos electrónicos causan interrupciones en los Servicios, Atemporal puede (sin limitación de otros recursos legales o contractuales que tenga) limitar o suspender tu acceso a las Herramientas de correo electrónico.</p>

          <h3 className="h3">19. Notificaciones.</h3>
          <p className="mb-4 pb-2">Puedes recibir notificaciones por correo electrónico o por correo postal ordinario en la dirección que figure en los registros de Atemporal. Los Servicios también pueden proporcionar notificaciones de cambios en estos Términos u otros asuntos mostrándote notificaciones o enlaces a notificaciones, por lo general, de los Servicios. Si deseas ponerte en contacto con Atemporal o enviar una notificación, puedes hacerlo en Atemporal, Inc., Attn: Legal Department, 535 Mission Street, 8th Floor, San Francisco, CA 94105, EE. UU. o mediante correo electrónico a ebmail(legal@Atemporal.com&#8594;mailto:legal@Atemporal.com).</p>

          <h3 className="h3">20. Modificaciones a los Términos o Servicios.</h3>
          <p className="mb-4 pb-2">Atemporal se reserva el derecho de modificar estos Términos de vez en cuando (colectivamente, &#34;Modificaciones&#34;). Si creemos que las Modificaciones son importantes, te informaremos sobre ellas haciendo una (o más) de las siguientes cosas (a) publicando los cambios a través de los Servicios; (b) actualizando la fecha de &#34;Actualización&#34; en la parte superior de esta página; o (c ) enviando un correo electrónico o un mensaje sobre las Modificaciones. Las Modificaciones que sean materiales entrarán en vigor treinta (30) días después de la fecha de &#34;Actualización&#34; o en la fecha que te comuniquemos en cualquier otra notificación. Las Modificaciones que simplemente aborden nuevas funciones que añadamos a los Servicios o que no te impongan cargas u obligaciones adicionales serán efectivas inmediatamente. Eres responsable de revisar y familiarizarte con cualquier Modificación. Tu uso continuado de los Servicios después de las Modificaciones constituye tu aceptación de esas Modificaciones y los Términos actualizados. En determinadas circunstancias, Atemporal puede solicitar una Modificación de estos Términos que solo se te aplicará a ti. Este tipo de Modificación debe realizarse a través de un documento escrito o electrónico firmado por ti y un funcionario autorizado de Atemporal. Los productos y servicios de Atemporal están en constante evolución con el fin de satisfacer las necesidades de nuestros Usuarios. Debido a esto, no podemos garantizar la disponibilidad de ciertas características o funcionalidades del producto. Atemporal se reserva el derecho a modificar, reemplazar o suprimir cualquier parte de los Servicios o de todo el Servicio.</p>

          <h3 className="h3">21. Asignación.</h3>
          <p className="mb-4 pb-2">Podemos asignar los presentes Términos y nuestros derechos y obligaciones según estos Términos sin tu consentimiento ni aprobación, a una filial u otra entidad en relación con una transacción corporativa o de otro tipo.</p>

          <h3 className="h3">22. Acuerdo completo.</h3>
          <p className="mb-4 pb-2"> Salvo que se indique lo contrario en el presente documento, los presentes Términos constituyen el acuerdo completo entre Atemporal y tú, y rigen el uso que haces de los Servicios y suceden a cualquier acuerdo, propuesta, discusión o comunicación anteriores o vigentes entre Atemporal y tú sobre el fondo del presente documento, distinto a cualquier otro acuerdo de Servicios por escrito entre tú y un ejecutivo autorizado de Atemporal en lo relacionado con un evento o eventos específicos.</p>

          <h3 className="h3">23. Ley Aplicable y Jurisdicción</h3>
          <p className="mb-4 pb-2">Estos Términos se rigen por las leyes del Estado de California, sin tener en cuenta las reglas de conflicto de leyes. Estas leyes se aplicarán sin importar en qué parte del mundo vivas. Pero si vives fuera de los Estados Unidos, puedes tener derecho a la protección de las disposiciones de protección al consumidor obligatorias de tu ley local de protección al consumidor. Atemporal tiene su sede en San Francisco, California, y cualquier acción legal contra Atemporal relacionada con nuestros Servicios y que no esté excluida por las disposiciones de arbitraje en estos Términos debe presentarse y llevarse a cabo en San Francisco. Por lo tanto, para cualquier acción no sujeta a arbitraje, tú y Atemporal acuerdan someterse a la jurisdicción personal de los tribunales federales o estatales (según corresponda) ubicados en el condado de San Francisco, California.</p>

          <h3 className="h3">24. Comentarios</h3>
          <p className="mb-4 pb-2">Agradecemos y te animamos a que envíes comentarios, opiniones y sugerencias para mejorar los Servicios (&#34;Comentarios&#34;). Cualquier Comentario que nos envíes se considerará no confidencial y no de tu propiedad. Al enviarnos tus Comentarios, nos otorgas una licencia no exclusiva, mundial, sin derechos de autor, irrevocable, sublicenciable y perpetua para utilizar y publicar esas ideas y materiales para cualquier propósito, sin compensación para ti.</p>

          <h3 className="h3">25. Sitios web de terceros; Cuentas vinculadas; Ofertas de terceros</h3>
          <p className="mb-4 pb-2">Los Servicios o Usuarios pueden proporcionar enlaces a otros recursos o sitios web de Internet. Dado que Atemporal no tiene control sobre dichos sitios web y recursos, reconoces y aceptas que Atemporal no es responsable de la disponibilidad de tales sitios web o recursos, y no promociona ni se responsabiliza de ningún Contenido, publicidad, ofertas, productos, servicios u otros materiales que aparezcan o estén disponibles en dichos sitios web o recursos, ni de los daños o pérdidas relacionados, aunque dichos sitios web y recursos estuvieran conectados con los socios o proveedores de servicios de Atemporal. Por ejemplo, si compras un seguro de boletos en Atemporal a un tercero, tu relación contractual es con el tercero proveedor del seguro de boletos, no con Atemporal.</p>

          <h3 className="h3">26. Disposiciones varias adicionales</h3>
          <p className="mb-4 pb-2">Nuestra incapacidad para hacer cumplir cualquier parte de estos Términos no constituirá una renuncia a nuestro derecho a aplicar más adelante esa o cualquier otra parte de estos Términos. Ninguna renuncia, enmienda o modificación oral de estos Términos entrará en vigor. Si se determina que alguna disposición de estos Términos es inaplicable, esa parte se limitará a la extensión mínima necesaria, las demás disposiciones de estos Términos permanecerán en pleno vigor y efecto. Los títulos de las Secciones de estos Términos se incluyen solo para garantizar la comodidad y no tienen efecto jurídico ni contractual. Estos Términos no crean ningún contratista independiente, agencia, sociedad, empresa conjunta u otra relación de este tipo. Podemos asignar libremente cualquiera de nuestros derechos y obligaciones bajo estos Términos. Podemos traducir estos Términos a otros idiomas para tu conveniencia. Si hay un conflicto entre la versión en inglés y la versión traducida, prevalecerá la versión en inglés.</p>

          <h3 className="h3">27. Cláusulas adicionales para Usuarios en ciertas ubicaciones</h3>
          <p className="mb-4 pb-2">Atemporal es una empresa global que ofrece a los Organizadores y Consumidores la oportunidad de beneficiarse de nuestros Servicios en todo el mundo. Para permitir que cada Usuario aproveche al máximo nuestros Servicios y la ley aplicable, es posible que ciertas disposiciones adicionales incluidas en esta Sección te sean aplicables.</p>
          </div>
        </div>
      </div>
    </section>
  )
}
