import React from 'react'

export const NoticePrivacyPage = () => {
  return (
    <section className="container mb-5 pt-4 pb-2 py-mg-4">
      <div className="row gy-4">
        {/* Content */}
        <div className="col-lg-9">
          <h2 className="h4">Aviso de privacidad</h2>
          <p className="mb-4 pb-2">Atemporal AC</p>
          {/* Video */}
          <div className="gallery mb-4 pb-2" data-video="true">
            <a href="https://www.youtube.com/watch?v=LDb-G8y88Sc" className="gallery-item video-item is-hovered rounded-3">
              <img src="assets/img/home/bg1.jpg" alt="Video preview" />
            </a>
          </div>

          <h3 className="h3">Quiénes somos</h3>
          <div className="texto-justificado">
          <h4 className="h4">1. Servicios de Atemporal.</h4>
          <p className="mb-4 pb-2">¡Te damos la bienvenida a Atemporal! Somos una plataforma de venta de entradas y registro cuyo objetivo es conectar el mundo a través de experiencias en vivo. Gracias a nuestros servicios y plataforma, ofrecemos a personas de todo el mundo la posibilidad de crear, descubrir y compartir eventos, así como de registrarse en ellos.</p>
          <p className="mb-4 pb-2">Si tienes alguna pregunta o duda, ponte en contacto con nosotros escribiendo a la dirección  privacidad@atemporal.art.</p>

          <h4 className="h4">2. Nuestra declaración de privacidad.</h4>
          <p className="mb-4 pb-2">La presente Política de privacidad establece la política con respecto a la información que se puede asociar a, o que se relaciona con, una persona específica y podría usarse para identificar a una persona (&#34;Datos personales&#34;) que se recopilan de los Usuarios en o a través de los Servicios. Esta política también cubre los datos personales recopilados de clientes y posibles clientes de ventas de Atemporal. Nos tomamos muy en serio la privacidad de tus Datos personales. Por esa razón, hemos redactado la presente Política de privacidad. Lee esta Política de privacidad, ya que incluye información importante acerca de tus Datos personales y otro tipo de información.</p>
          <p className="mb-4 pb-2">Por tanto, los &#34;Datos no personales&#34; tal y como se usan en esta Política de privacidad, son cualquier tipo de información que no se relacione con una persona o que no se pueda usar para identificar a una persona. Cuando interactúas con los Servicios, podemos recopilar Datos no personales. Las limitaciones y los requisitos en esta Política de privacidad sobre nuestro uso, recopilación, divulgación, transferencia y almacenamiento o retención de Datos personales no se aplican a los Datos no personales.</p>

          <h4 className="h4">3. Datos personales que recopilamos.</h4>
          <p className="mb-4 pb-2">Cuando interactúas con nosotros a través de los Servicios, o te involucras con Atemporal como cliente o posible cliente de ventas, podemos recopilar Datos personales. A veces esto será en nuestro propio nombre y otras veces será en nombre de un Organizador que utiliza nuestros Servicios para llevar a cabo un evento. Esta es una distinción importante a efectos de ciertas leyes de protección de datos y se explica con más detalle abajo.</p>
          <h5 className="h5">3.1 Información recopilada de todos los Usuarios.</h5>
          <p className="mb-4 pb-2">Información que nos proporcionas: al igual que hacemos con todos los Usuarios, recopilamos Datos personales cuando proporcionas de forma voluntaria dicha información a los Servicios (por ejemplo, al registrarte para acceder a los Servicios, al ponerte en contacto con nosotros para resolver dudas, al responder a una de nuestras encuestas o al examinar o usar ciertas partes de los Servicios). Los Datos personales que podemos recopilar incluyen sin limitación, tu nombre, dirección, dirección de correo electrónico y cualquier otra información que decidas proporcionar y/o que permita la identificación personal de los Usuarios. Información que recopilamos automáticamente: asimismo, recopilamos de manera automática ciertos datos técnicos que recibimos del ordenador, dispositivo móvil o navegador a través del cual accedes a los Servicios (&#34;Datos automáticos&#34;). Entre los Datos automáticos se incluyen sin limitación, un identificador único asociado a tu navegador o dispositivo de acceso, (incluidos, por ejemplo, tu dirección IP (Internet Protocol)), características sobre tu dispositivo de acceso o navegador, estadísticas sobre tus actividades en los Servicios, información sobre cómo llegaste a los Servicios y datos recopilados a través de cookies, etiquetas de píxel, objetos compartidos localmente, almacenamiento web y otras tecnologías similares. Encontrarás más información sobre cómo usamos cookies y otras tecnologías de seguimiento similares en nuestra Declaración de cookies. Al registrarte para los Servicios o, por lo demás, al enviarnos Datos personales, podemos asociar otros Datos no personales (incluidos Datos no personales que recopilamos de terceros) con tus Datos personales. En tal caso, trataremos todos aquellos datos combinados pertinentes como si se tratara de tus Datos personales hasta el momento en que ya no se puedan asociar a ti o usar para identificarte.</p>
          <h5 className="h5">3.2 Información recopilada de los Organizadores.</h5>
          <p className="mb-4 pb-2">Si eres un Organizador, recopilaremos Datos personales adicionales sobre ti. Información que nos proporcionas: en ciertos casos, es posible que recopilemos datos de tu tarjeta de crédito (por ejemplo, el número de la tarjeta de crédito, la fecha de caducidad, la dirección de facturación, etc.), de los cuales algunos pueden ser Datos personales, con el fin de asegurar determinados pagos. Además, si usas nuestros servicios de procesamiento de pagos, recopilaremos información financiera tuya (por ejemplo, información de tu cuenta bancaria o una dirección a la que enviar cheques) que resulte necesaria para facilitar los pagos y la información necesaria por razones tributarias (por ejemplo, tu número de identificación de contribuyente). Información que obtenemos de otras fuentes: Es posible que también recopilemos o recibamos Datos personales, incluidos tu nombre, dirección de correo electrónico y otra información de contacto, de fuentes de terceros como, por ejemplo, sitios web de terceros y socios de marketing, tu banco, nuestros socios de procesamiento de pagos y agencias de información de solvencia.</p>
          <h5 className="h5">3.3 Información recopilada de los Consumidores.</h5>
          <p className="mb-4 pb-2">Si eres un Consumidor, recopilaremos Datos personales adicionales de ti, a veces para nuestros propios fines y otras veces en nombre de un Organizador (consulta la sección 16 a continuación para obtener más información).</p>
          <p className="mb-4 pb-2">Información que proporcionas a través de las Propiedades o Aplicaciones de Atemporal: si te registras para un evento de pago, proporcionarás información financiera (por ejemplo, el número de la tarjeta de crédito, la fecha de caducidad, la dirección de facturación, etc.) y algunos de esos datos pueden ser Datos personales. Además, los Organizadores pueden configurar páginas de registro en eventos para recopilar prácticamente todo tipo de información de los Consumidores en relación con el registro en un evento de un Organizador que se encuentre en la lista de los Servicios. Atemporal no controla el proceso de registro de un Organizador ni los Datos personales que recopilan. Al registrarte en o, por lo demás, proporcionar información a Atemporal relacionada con un evento o una actividad de un Organizador, tanto si esa información es tuya o de un tercero, relacionada con una compra, registro o cambio, ese Organizador la recibirá y es posible que use la información que le proporciones. Consulta la Sección 5.5 a continuación, titulada &#34;Cómo revelamos y transferimos tus datos personales: Organizadores&#34; para obtener más información sobre la recepción y uso de tus datos por parte de un Organizador.</p>
          <p className="mb-4 pb-2">Información que obtenemos de otras fuentes: es posible que también recopilemos o recibamos Datos personales de fuentes de terceros como Organizadores, otros Consumidores, integraciones con redes sociales o con otros terceros, el banco que expidió tu tarjeta de crédito, nuestros socios de procesamiento de pagos u otros terceros.</p>
          <h5 className="h5">3.4 Información recopilada de clientes y clientes potenciales de ventas</h5>
          <p className="mb-4 pb-2">Si interactúas con el equipo de ventas de Atemporal, podemos recopilar lo siguiente: tu nombre, correo electrónico, dirección, número de teléfono y otra información de contacto profesional. Si interactúas con el equipo de ventas y das tu consentimiento para grabar una reunión, el equipo de ventas puede recopilar grabaciones de audio y/o vídeo de ti.</p>

          <h4 className="h4">4. Cómo utilizamos tus datos personales.</h4>
          <p className="mb-4 pb-2">Recopilamos y usamos los Datos personales recopilados de manera consecuente con esta Política de privacidad, y leyes de privacidad aplicables. Podemos utilizar los Datos personales de la siguiente manera:</p>
          <h5 className="h5">4.1 Razón específica.</h5>
          <p className="mb-4 pb-2">Si proporcionas Datos personales para un fin en concreto, podremos usarlos para lo relacionado con el fin para el cual se proporcionaron. Por ejemplo, si te pones en contacto con nosotros por correo electrónico, utilizaremos los Datos personales que nos facilites para responder a tu pregunta o solucionar el problema, y responderemos a la dirección de correo electrónico desde la que se envió el mensaje.</p>
          <h5 className="h5">4.2 Acceso y uso.</h5>
          <p className="mb-4 pb-2">Si proporcionas Datos personales con el fin de obtener acceso a los servicios o utilizarlos, o cualquier otra función relacionada, utilizaremos dichos Datos personales para proporcionarte acceso a los servicios o funciones o para utilizarlos, así como a fin de analizar el uso de dichos Servicios o funciones. Por ejemplo, si proporcionas Datos personales sobre tu identidad o idoneidad para utilizar ciertas partes de los Servicios, usaremos dicha información para tomar una decisión sobre si permitirte acceder al uso de dichos Servicios y evaluar de forma continua tu idoneidad para su uso.</p>
          <h5 className="h5">4.3 Fines comerciales internos.</h5>
          <p className="mb-4 pb-2">Podemos usar tus Datos personales para fines comerciales internos, incluyendo sin limitación, para ayudarnos a mejorar el contenido y la funcionalidad de los Servicios, comprender mejor a nuestros Usuarios, mejorar los Servicios, proteger, identificar o abordar actividades fraudulentas, hacer cumplir nuestros Términos de servicio, gestionar tu cuenta y proporcionarte servicio de atención al cliente y, de manera general, gestionar los Servicios y nuestra actividad comercial.</p>
          <h5 className="h5">4.4 Marketing de Atemporal y Organizador.</h5>
          <p className="mb-4 pb-2">Podemos utilizar tus Datos personales para nuestros fines de marketing y publicidad, incluidos (sin limitación) por correo electrónico, marketing por SMS, medios de visualización y destinados a otros dispositivos (como tablets, dispositivos móviles y televisores). Hacemos esto con el fin de informarte sobre servicios o eventos que creemos que pueden ser de tu interés, desarrollar materiales promocionales o de marketing y mostrar contenido de Atemporal o relacionado con eventos y publicidad dentro o fuera de los Servicios que creemos que pueden ser de tu interés. También podemos hacer esto en nombre de un Organizador, por ejemplo, cuando tus interacciones previas con un Organizador sugieren que puedes estar interesado en un tipo particular de evento. Consulta &#34;Cancelar la suscripción a mensajes electrónicos&#34;, a continuación, sobre cómo quedar excluido de diversas comunicaciones de marketing de Atemporal.</p>
          <p className="mb-4 pb-2">Es posible que veas anuncios de nuestros Servicios en sitios web de terceros, incluidas las plataformas de redes sociales. También proporcionamos herramientas a los Organizadores para ayudarles a mostrar anuncios para sus eventos en sitios web de terceros y plataformas de redes sociales. Si ves un anuncio en un sitio web de un tercero o en una plataforma de redes sociales, puede deberse a que nosotros o el Organizador hemos contratado al tercero o a la plataforma de redes sociales para que muestre el anuncio a Usuarios, o a otras personas que tengan atributos similares a los de nuestros Usuarios. En algunos casos, esto implica compartir tu dirección de correo electrónico u otros datos de contacto con el tercero o la plataforma de redes sociales para que puedan identificarte como uno de nuestros Usuarios, o identificar a otros individuos con atributos similares a los tuyos con el fin de mostrarles anuncios para nuestros Servicios (o para los eventos de nuestro Organizador). Si ya no deseas que tus Datos personales se utilicen para estos fines, ponte en contacto con nosotros en privacidad@atemporal.art. Si se trata de la publicidad de un Organizador, puede que tengas que contactar directamente con el Organizador. Para obtener más información sobre cómo nosotros y los Organizadores comercializamos e interactuamos con sitios de redes sociales, consulta la sección 5.6.</p>
          <h5 className="h5">4.5 Correos electrónicos del Organizador.</h5>
          <p className="mb-4 pb-2">Permitimos a los Organizadores utilizar nuestras herramientas de correo electrónico para que se pongan en contacto con los Consumidores acerca de sus eventos actuales y pasados, por lo que es posible que recibas mensajes de correo electrónico de dichos Organizadores procedentes de nuestro sistema y que enviamos en su nombre. Si te has registrado para un evento en los Servicios, tu dirección de correo electrónico estará disponible para ese Organizador. No obstante, los Organizadores también pueden importar las direcciones de correo electrónico que tienen de fuentes externas y enviar comunicaciones a través de los Servicios a dichas direcciones, por lo que enviaremos esas comunicaciones a tales direcciones de correo electrónico en nombre del Organizador. El Organizador, y no Atemporal, es el responsable de enviar estos correos electrónicos. Consulta la sección &#34;Cancelar la suscripción a mensajes electrónicos&#34;, que aparece más adelante, para obtener información sobre cómo quedar excluido de este tipo de comunicaciones iniciadas por el Organizador.</p>
          <h5 className="h5">4.6 Uso de datos basados en intereses</h5>
          <p className="mb-4 pb-2">A veces deducimos el tipo de eventos o actividades que te pueden interesar. Podemos utilizar estas deducciones para ayudar a focalizar la publicidad o personalizar las recomendaciones para ti, incluso en nombre de los Organizadores. Podemos hacer esto de manera agregada o generalizada. Por ejemplo, podemos determinar que nuestros usuarios que asisten a muchos eventos de comedia también asisten o muestran interés por eventos o contenidos relacionados con la resistencia. Podemos dirigir (o ayudar a dirigir) contenido o recomendaciones relacionadas tanto con la comedia como con la resistencia a esos Usuarios.</p>
          <h5 className="h5">4.7 Otros fines.</h5>
          <p className="mb-4 pb-2">Si quisiéramos utilizar tus Datos personales de manera consecuente con la presente Política de privacidad, se te informará antes de dicho uso o en el momento en que se recopilen dichos Datos personales, u obtendremos tu consentimiento tras su recopilación, pero siempre antes de hacer uso de ellos.</p>
          <h5 className="h5">4.8 Datos personales agregados.</h5>
          <p className="mb-4 pb-2">En un esfuerzo continuado por comprender y prestar un mejor servicio a nuestros usuarios, realizamos frecuentemente informes de datos demográficos, intereses y comportamiento de nuestros clientes basados en los Datos personales y cualquier otro tipo de información que hayamos recopilado. Esta investigación generalmente se lleva a cabo solo de manera agregada, por lo que no te identifica. Una vez que los Datos personales se encuentran en forma agregada, a los efectos de esta Política de privacidad, se convierten en Datos no personales.</p>

          <h4 className="h4">5. Cómo revelamos y transferimos tus datos personales.</h4>
          <h5 className="h5">5.1 Fondo.</h5>
          <p className="mb-4 pb-2">No hacemos negocio vendiendo tus Datos personales. Consideramos que esta información es una parte vital de nuestra relación contigo. Por lo tanto, no venderemos tus Datos personales a terceros, incluidos terceros publicitarios. Existen algunas circunstancias bajo las cuales podríamos revelar, transferir o compartir tus Datos personales con determinados terceros sin que te lo notifiquemos, tal y como se indica en esta Política de privacidad.</p>
          <h5 className="h5">5.2 Transferencias de negocio.</h5>
          <p className="mb-4 pb-2">A medida que desarrollamos nuestro negocio, podríamos comprar o vender negocios o activos. En caso de venta, fusión, reorganización, disolución corporativa o evento similar, los Datos personales podrían formar parte de los activos transferidos. También podríamos revelar tus Datos personales en el curso de la debida diligencia para tal evento. Reconoces y aceptas que cualquier sucesor o comprador de Atemporal (o sus activos) siga teniendo el derecho a utilizar tus Datos personales y otro tipo de información de acuerdo con los términos de la presente Política de privacidad.</p>
          <h5 className="h5">5.3 Sociedades matrices, subsidiarias y filiales.</h5>
          <p className="mb-4 pb-2">También podríamos compartir tus Datos personales con nuestras sociedades matrices, subsidiarias y/o filiales para fines que se ajusten con la presente Política de privacidad. Nuestras sociedades matrices, subsidiarias y filiales estarán obligadas a conservar dichos Datos personales de acuerdo con esta Política de privacidad.</p>
          <h5 className="h5">5.4 Agentes, Asesores y Proveedores de servicios.</h5>
          <p className="mb-4 pb-2">Podemos compartir tus Datos personales con nuestros contratistas y proveedores de servicios que procesan Datos personales en nombre de Atemporal para realizar ciertas funciones relacionadas con el negocio. Estas empresas incluyen nuestras agencias de marketing, proveedores de publicidad en línea, proveedores de servicios de datos y de mejora de datos, proveedores de servicios de bases de datos, proveedores de servicios de copia de seguridad y recuperación de desastres, proveedores de servicios de correo electrónico, socios de procesamiento de pagos, atención al cliente, asistencia técnica, empresas de alojamiento y otros. Cuando contratamos a otras empresas para que realicen tales funciones, es posible que les proporcionemos información, incluidos los Datos personales, relacionada con la realización de dichas funciones.</p>
          <h5 className="h5">5.5 Organizadores.</h5>
          <p className="mb-4 pb-2">Además, cuando te registras para un evento, te inscribes para recibir comunicaciones, participas en un concurso o introduces tus Datos personales (por ejemplo, a través de un formulario web) para comunicarte con un Organizador o participar en un evento del Organizador, dicho Organizador recibirá esa información. Por ejemplo, si introduces tu nombre y dirección de correo electrónico en un formulario web para una oferta, actividad o evento del Organizador, este recibirá esa información. El Organizador podrá entonces enviarte comunicaciones de marketing o de otro tipo, que podrán estar sujetas a su propia política de privacidad por separado. Asimismo, si proporcionas tu número de teléfono móvil, puedes recibir mensajes de información relacionados con el servicio, evento, actividad o información objeto de tu interés.</p>
          <p className="mb-4 pb-2">Cuando compras entradas, te registras en un evento o realizas donaciones a un evento, cambias la entrada o el registro para un evento con otra persona, participas en un concurso o, por lo demás, introduces tus Datos personales (como a través de un formulario web) o te comunicas con un Organizador, o participas en, o muestras interés por, un evento o una actividad de un Organizador o en un Organizador, ese Organizador recibirá la información que proporciones, incluidos tus Datos personales y, en los casos en los que se realice un cambio de entrada o registro, también los Datos personales de a quién se realice el cambio. Otros terceros que estén involucrados en o en cuyo nombre se promocione un evento o actividad también pueden recibir esos Datos Personales. Por ejemplo, en el caso de las páginas de recaudación de fondos, podríamos facilitar tus Datos personales tanto a la organización benéfica que organiza la página de recaudación de fondos como al Organizador del evento al que está enlazada la página de recaudación de fondos. En algunos casos, un Organizador puede designar a un tercero, que puede estar o no afiliado con el Organizador, para que cree una página de evento o de recaudación de fondos en su nombre (a estos terceros los denominamos &#34;Terceros organizadores&#34;).</p>
          <p className="mb-4 pb-2">Por ejemplo, y sin limitación, el lugar de un concierto (el Organizador, en este caso) puede permitir que terceros, promotores o empresas de producción (los Terceros organizadores) creen eventos que se celebrarán en el lugar del Organizador utilizando su cuenta de Atemporal. En ese caso, podemos proporcionar tus Datos personales a los Terceros organizadores en nombre de los Organizadores. Lo mismo ocurre con los concursos y sorteos: podemos proporcionar tus Datos Personales tanto al Organizador que promueve el concurso o sorteo, como a cualquier patrocinador legal del concurso o sorteo (como un patrocinador de marca).</p>
          <p className="mb-4 pb-2">No somos responsables de las acciones llevadas a cabo por dichos Organizadores o sus Terceros organizadores (u otros destinatarios de tus Datos personales), en relación con tus Datos personales. Es importante que revises las políticas aplicables de los Organizadores y, en caso de ser aplicable y si están disponibles, de los Terceros organizadores, de un evento (y de la página de recaudación de fondos relacionada, si la hubiera) antes de facilitar Datos personales u otra información en relación con dicho evento o la página de recaudación de fondos relacionada. De manera similar, si eres miembro de la organización de un Organizador dentro de Atemporal, tus Datos Personales estarán disponibles para el Organizador y se compartirán con los Terceros organizadores a los que el Organizador haya otorgado permiso para ver a todos los miembros de la organización del Organizador.</p>
          <h5 className="h5">5.6 Facebook, redes sociales y otras conexiones de terceros.</h5>
          <p className="mb-4 pb-2">a. Conexión de tu cuenta de Atemporal a servicios de redes sociales. Podemos conectar tu cuenta de Atemporal con tus cuentas en servicios de terceros como Facebook. En ese caso, podríamos recopilar, utilizar, divulgar, transferir y almacenar/retener información relativa a tu cuenta con dichos servicios de terceros de acuerdo con la presente Política de privacidad. Por ejemplo, si realizas una conexión con Facebook, almacenaremos tu ID de Facebook, nombre, apellidos, correo electrónico, ubicación, lista de amigos e imagen de perfil, y utilizaremos estos datos para conectar con tu cuenta de Facebook a fin de proporcionar ciertas funciones en los Servicios como, por ejemplo, recomendar eventos en los que están interesados tus amigos de Facebook y compartir los eventos en los que estás interesado, o a los que asistes, con determinados grupos de personas (por ejemplo, tus amigos de Facebook).</p>
          <p className="mb-4 pb-2">b. &#34;Marcar con me gusta&#34; o &#34;Seguir&#34; a Atemporal en redes sociales. Además, cuando &#34;nos marcas con me gusta&#34; o &#34;nos sigues&#34; en Facebook, Instagram, Twitter u otros sitios de redes sociales (en la medida en que proporcionamos esa capacidad), podemos recopilar cierta información sobre ti, incluido tu nombre, dirección de correo electrónico y cualquier comentario o contenido que publiques que sea relevante para nosotros. Asimismo, podemos recopilar tu información si te inscribes en una de nuestras promociones o nos envías información a través de sitios de redes sociales.</p>
          <p className="mb-4 pb-2">c. Complementos y enlaces de Facebook en nuestras páginas. El sitio web de Atemporal también puede contener enlaces a Facebook, por ejemplo, a través del botón &#34;Me gusta&#34; o &#34;Compartir&#34; de Facebook u otros complementos sociales. Cuando interactúes con estas funciones y enlaces, tu navegador establecerá un enlace directo con los servidores de Facebook, y Facebook recibirá información sobre tu navegador y tu actividad, y podrá vincularla a tu cuenta de usuario de Facebook. Para obtener más información sobre cómo utiliza Facebook los datos, consulta las políticas de Facebook.</p>
          <p className="mb-4 pb-2">d. Marketing y conectividad adicional de Facebook por Organizadores. Además, si eres miembro de Facebook (u otra plataforma de redes sociales) y proporcionas Datos personales a un Organizador (por ejemplo, de la forma descrita en la Sección 5.5), el Organizador puede utilizar esos Datos personales para enviarte publicidad y ofertas a través de Facebook (u otra plataforma de redes sociales), incluso cuando estás en Facebook u otra plataforma de redes sociales. El Organizador puede utilizar herramientas que proporcionemos nosotros y también podrá trabajar con terceros para hacer posible esta integración de datos y publicidad. Facebook y otras plataformas de redes sociales pueden proporcionar una forma de optar por no participar en este tipo de publicidad. Revisa sus ajustes de usuario y sus páginas de asistencia para obtener más información sobre cómo te ayudan a gestionar las opciones de privacidad y de marketing.</p>
          <p className="mb-4 pb-2">e. Servicios e integraciones de terceros. Atemporal puede proporcionarte la oportunidad de contratar directamente con terceros y/o de integrarte con servicios o aplicaciones de terceros, a través de nuestra plataforma. En tales casos, revelaremos tus Datos personales a otras entidades con el fin de cumplir con una solicitud tuya, o para proporcionarte los servicios que hayas solicitado.</p>
          <h5 className="h5">5.7 Requisitos legales.</h5>
          <p className="mb-4 pb-2">Podemos divulgar tus Datos personales si así lo exige la ley para (por ejemplo) en caso de una citación judicial o una solicitud de un organismo gubernamental (incluidas respuestas a autoridades públicas para cumplir requisitos de seguridad nacional o cumplimiento de la ley), o si creemos de buena fe que dicha acción es necesaria (a) para cumplir con una obligación jurídica; (b) para proteger o defender nuestros derechos, intereses o propiedades, o los de un tercero; (c) para prevenir o investigar posibles delitos en relación con los Servicios; (d) para actuar en circunstancias de urgencia para proteger la seguridad personal de los Usuarios de los Servicios o el público en general; o (e) como protección ante responsabilidades jurídicas.</p>

          <h4 className="h4">6. Cómo almacenamos tus datos personales.</h4>
          <p className="mb-4 pb-2">Podemos almacenar los Datos personales propiamente dichos o transferirlos a un tercero que los almacenará de conformidad con esta Política de privacidad. Adoptamos las medidas que consideramos razonables para proteger los Datos personales recopilados por los Servicios contra pérdida, mal uso, uso no autorizado, acceso no autorizado, divulgación involuntaria, modificación y destrucción. Sin embargo, no existen redes, servidores, bases de datos ni transmisiones por Internet o correo electrónico completamente seguras o exentas de errores. Por lo tanto, debes tener especial cuidado al decidir qué tipo de información nos envías por medios electrónicos. Debes tener esto en cuenta cuando divulgues Datos personales.</p>

          <h4 className="h4">7. Cómo acceder a tus Datos personales, actualizarlos, corregirlos o eliminarlos.</h4>
          <p className="mb-4 pb-2">Puedes acceder a tus Datos personales que almacenamos o eliminarlos. Si eres un Usuario registrado, puedes hacerlo iniciando sesión y visitando la página Ajustes de la cuenta para descargar una copia de tus Datos personales en formato de lectura mecánica y/o eliminar tus Datos personales. También puedes editar algunos de tus datos personales directamente a través de tu cuenta. En ciertos caso, puedes pedirnos que corrijamos y actualicemos cualquiera de tus Datos personales incorrectos mediante la información de contacto que viene a continuación, y consideraremos tu solicitud de acuerdo con las leyes aplicables.</p>
          <p className="mb-4 pb-2">Si un Consumidor inicia una solicitud de eliminación de datos, Atemporal está autorizada a eliminar o anonimizar los Datos personales del Consumidor solicitante de los Servicios, incluso si eso significa eliminar su disponibilidad para el Organizador a través de los Servicios. Sin embargo, si eres un Consumidor, comprendes que incluso si Atemporal elimina o anonimiza tus Datos personales cuando lo solicites o de conformidad con esta Política, tus Datos personales aún pueden estar disponibles en las bases de datos del Organizador si se transmiten al Organizador antes de que Atemporal reciba o tome medidas en cualquier actividad de eliminación o anonimización.</p>
          <p className="mb-4 pb-2">Los Usuarios no registrados también pueden acceder a, actualizar, corregir o eliminar Datos personales y ejercer estos derechos mediante la información de contacto que viene a continuación. Tomaremos en cuenta y responderemos a todas las peticiones de conformidad con la ley aplicable.</p>

          <h4 className="h4">8. Durante cuánto tiempo conservamos tus Datos personales.</h4>
          <p className="mb-4 pb-2">Podemos conservar tus Datos personales mientras estés registrado para usar los Servicios. Puedes eliminar tu cuenta si visitas la página Ajustes de la cuenta. Sin embargo, podemos conservar Datos personales durante más tiempo si las leyes aplicables así lo permiten o lo exigen. Aunque eliminemos tus Datos personales, estos pueden seguir existiendo en soportes de archivo o copia de seguridad durante un tiempo adicional por motivos legales, fiscales o reguladores o por fines comerciales legítimos y legales. Para clientes y posibles clientes de ventas, conservamos sus datos mientras mantengamos una relación contigo y durante un periodo limitado de tiempo posterior  necesario para cumplir con los requisitos comerciales y legales.</p>

          <h4 className="h4">9. Cookies, etiquetas de píxel, objetos locales compartidos, almacenamiento web y tecnologías similares.</h4>
          <p className="mb-4 pb-2">Consulta nuestra Declaración de cookies para obtener más información sobre nuestro uso de cookies y otras tecnologías de seguimiento similares.</p>

          <h4 className="h4">10. Tus opciones.</h4>
          <p className="mb-4 pb-2">Ponemos diversas opciones a tu disposición en relación con tus Datos personales:</p>
          <h5 className="h5">10.1 Limitar los Datos personales que facilitas.</h5>
          <p className="mb-4 pb-2">Puedes utilizar los Servicios sin aportar ningún Dato personal (más allá de los Datos automáticos, en la medida en que la legislación aplicable los considere Datos personales) o limitando los Datos personales que facilitas. Si decides no facilitar ningún Dato personal o limitar los Datos personales proporcionados, es posible que no puedas utilizar algunas funciones de los Servicios. Por ejemplo, para comprar entradas como Consumidor, deberás facilitar tu nombre y dirección de correo electrónico al Organizador.</p>
          <h5 className="h5">10.2 Cancelar la suscripción a mensajes electrónicos.</h5>
          <p className="mb-4 pb-2">(a) Comunicaciones de marketing de Atemporal. Donde esté de acuerdo con nuestras preferencias de marketing, Atemporal puede enviarte mensajes electrónicos con contenidos publicitarios o de marketing sobre los Servicios propiamente dichos o eventos de los Servicios si te has registrado en los Servicios, has adquirido una entrada o te has registrado en un evento de los Servicios. También puedes elegir &#34;dejar de recibir&#34; estos mensajes electrónicos haciendo clic en el enlace &#34;Anular suscripción&#34; en la parte inferior de dichos mensajes. Además, también puedes gestionar tus preferencias de correo electrónico en todo momento iniciando sesión (o creando una cuenta e iniciando sesión), haciendo clic en &#34;Cuenta&#34; y seleccionando &#34;Preferencias de correo electrónico&#34;.</p>
          <p className="mb-4 pb-2">(b) Mensajes enviados por el Organizador. Los organizadores pueden utilizar nuestras herramientas de correo electrónico para enviar mensajes electrónicos a las personas en sus listas de suscripción, incluidos los Consumidores que se han registrado en sus eventos utilizando los Servicios. Aunque estos mensajes electrónicos se envían a través de nuestro sistema, Atemporal no determina su contenido ni sus destinatarios. Se exige a los organizadores que utilicen nuestras herramientas de correo electrónico únicamente en virtud de las leyes aplicables. Atemporal ofrece el enlace &#34;Anular suscripción&#34; en todos estos correos electrónicos, lo que permite a los destinatarios elegir dejar de recibir mensajes electrónicos de un Organizador en particular.</p>
          <p className="mb-4 pb-2">(c ) Notificaciones sociales. Si conectas tu cuenta de Facebook o te registras en integraciones con otras redes sociales cuyas funciones incluyan notificaciones sociales (es decir, actualizaciones sobre las acciones de tus amigos en los Servicios), recibirás dichas notificaciones. Puedes gestionar estas notificaciones ajustando las configuraciones sociales como privadas o desconectando la integración.</p>
          <p className="mb-4 pb-2">(d) Mensajes de respuesta o sobre transacciones. Algunos mensajes electrónicos de Atemporal se envían en respuesta a tus solicitudes. Por ejemplo, si eres un Consumidor, debemos enviarte la entrada o el registro por correo electrónico en nombre del Organizador cuando adquieras dicha entrada o registro. Otro ejemplo sería que, si envías un correo electrónico al departamento de atención al cliente, te enviaremos un correo electrónico para responderte. Sin perjuicio de las suscripciones que hayas anulado, seguirás recibiendo estos correos electrónicos de respuesta o sobre transacciones. Solo puedes dejar de recibir correos electrónicos de este tipo contactándonos. Al elegir dejar de recibir todos los mensajes electrónicos de nuestra parte o a través de nuestro sistema, dejarás de recibir actualizaciones acerca de eventos que hayas creado (incluidas emisiones de pagos) o en los que estés registrado como asistente (incluidos los correos electrónicos con tus entradas). No es recomendable hacer esto a menos que planees dejar de hacer uso de los Servicios, no estés actualmente registrado en un evento, no estés actualmente organizando un evento y no necesites recibir mensajes nuestros o a través de nuestro sistema.</p>
          <p className="mb-4 pb-2">(e) Retención. La tramitación de tu solicitud de anulación de suscripción puede tardar hasta cuarenta y ocho (48) horas en completarse. Incluso si decides dejar de recibir todo tipo de mensajes electrónicos, seguiremos conservando tus datos Personales de acuerdo con esta Política de privacidad, pero ya no los usaremos para ponernos en contacto contigo. No obstante, aquellos organizadores que ya hayan recibido tus Datos personales de acuerdo con lo estipulado en esta Política de privacidad podrán seguir usando esa información para ponerse en contacto contigo de acuerdo con sus propias Políticas de privacidad, pero no podrán usar nuestro sistema a tal efecto.</p>
          <h5 className="h5">10.3 No realizar seguimiento.</h5>
          <p className="mb-4 pb-2">Actualmente no participamos en ningún marco &#34;No realizar seguimiento&#34; que nos permita responder a señales u otros mecanismos que nos envíes en relación con la recogida de tus Datos personales.</p>

          <h4 className="h4">11. Exclusiones.</h4>
          <h5 className="h5">11.1 Datos personales proporcionados a terceros.</h5>
          <p className="mb-4 pb-2">Esta Política de privacidad no rige sobre Datos personales que proporciones a otro Usuario o visitante a través de los Servicios o por cualquier otra vía, incluidos datos facilitados a Organizadores en páginas de eventos o información que publiques en una de las zonas públicas de los Servicios.</p>
          <h5 className="h5">11.2 Enlaces de terceros.</h5>
          <p className="mb-4 pb-2">Esta Política de privacidad sólo es de aplicación para los Servicios. Los Servicios pueden contener enlaces a otros sitios web no controlados por nosotros (&#34;Sitios de terceros&#34;). Las políticas y procedimientos que se describen aquí no son aplicables a los Sitios de terceros. Los enlaces desde los Servicios no implican que apoyemos o hayamos examinado los Sitios de terceros. Te recomendamos que te pongas en contacto directamente con dichos sitios para obtener información sobre sus políticas de privacidad.</p>

          <h4 className="h4">12. Niños - Ley de protección de la privacidad en línea para niños.</h4>
          <p className="mb-4 pb-2">No almacenamos de manera intencionada Datos personales de niños menores de trece (13) años. Si tienes menos de trece (13) años, no envíes Datos personales a través de los Servicios. Animamos a los padres y tutores legales a que supervisen el uso que hacen los menores de Internet y ayuden a aplicar nuestra Política de privacidad enseñando a sus hijos a que nunca faciliten Datos personales a través de los Servicios sin su consentimiento. Si tienes razones para creer que un menor de 13 años nos ha facilitado Datos personales a través de los Servicios, contáctanos y haremos todo lo posible para eliminar dicha información de nuestras bases de datos.</p>

          <h4 className="h4">13. Leyes internacionales de privacidad.</h4>
          <p className="mb-4 pb-2">Si accedes a los Servicios desde fuera de los México, ten en cuenta que estás enviando información (incluyendo Datos personales) a los México, donde se encuentran nuestros servidores. Dicha información podría transferirse dentro de los México o de vuelta de los México a otros países fuera de tu país de residencia dependiendo del tipo de información del que se trate y de la manera en que la almacenamos. Es posible que estos países (incluidos los México) no tengan necesariamente leyes de protección de datos tan exhaustivas o protectoras como las de tu país de residencia; sin embargo, nuestra recopilación, almacenamiento o uso de tus Datos personales seguirá rigiéndose en todo momento por esta Política de privacidad.</p>

          <h4 className="h4">14. Cambios en esta Política de privacidad.</h4>
          <p className="mb-4 pb-2">Los Servicios y nuestro negocio pueden cambiar. Como resultado, en ocasiones, podríamos necesitar realizar cambios en esta Política de privacidad. Nos reservamos el derecho, a nuestra entera discreción, de actualizar o modificar la presente Política de privacidad en cualquier momento (colectivamente, &#34;Modificaciones&#34;). Las Modificaciones de la presente Política de privacidad se publicarán en el Sitio con la nueva fecha de &#34;Actualización&#34; en la parte superior de dicha Política de privacidad. En determinadas circunstancias, Atemporal podría, sin estar obligado a ello, proporcionarte un aviso adicional de dichas Modificaciones, por ejemplo, mediante notificaciones por correo electrónico o dentro del Servicio. Las Modificaciones entrarán en vigor treinta (30) días después de la fecha de &#34;Actualización&#34; o en la fecha que te comuniquemos en cualquier otro aviso.</p>
          <p className="mb-4 pb-2">Consulta esta política periódicamente, especialmente antes de facilitar Datos personales. Esta Política de privacidad se actualizó en la fecha indicada arriba. El uso continuado de los Servicios tras la entrada en vigor de cualquier Modificación de la presente Política de privacidad constituirá tu aceptación de dichas Modificaciones. Si no aceptas todas las Modificaciones de esta Política de privacidad, debes dejar de acceder a los Servicios, navegar por ellos y utilizarlos de cualquier otro modo.</p>

          <h4 className="h4">15. Resolución de disputas.</h4>
          <p className="mb-4 pb-2">Si tienes alguna queja sobre las prácticas de privacidad de Atemporal, escríbenos a la siguiente dirección: privacidad@atemporal.art </p>

          <h5 className="h5">Base legal para procesar tus Datos personales</h5>
          <p className="mb-4 pb-2">El RGPD requiere que te informemos sobre la base legal en la que confiamos para procesar tus Datos personales. Los motivos legales por los que procesamos tus Datos personales para los fines establecidos en la Sección 4 anterior serán normalmente los siguientes:</p>
          <ul className="mb-4 pb-2 ps-4">
            <li className="mb-1">Has otorgado tu consentimiento;</li>
            <li className="mb-1">Es necesario para nuestra relación contractual;</li>
            <li className="mb-1">El procesamiento es necesario para que cumplamos con nuestras obligaciones legales o reglamentarias; y/o</li>
            <li className="mb-1">El procesamiento es en nuestro interés legítimo como una plataforma de organización de eventos y venta de entradas (por ejemplo, para proteger la seguridad y la integridad de nuestros sistemas y para proporcionarte servicio al cliente, etc.).</li>
            </ul>
            <h5 className="h5">Transferencias de datos personales</h5>
            <p className="mb-4 pb-2">Como Atemporal es una empresa global, es posible que tengamos que transferir tus Datos personales fuera del país desde el que se proporcionaron originalmente. Esto puede ser intragrupo o a países terceros con los que trabajamos y que pueden estar ubicados en jurisdicciones fuera de México.</p>
            <p className="mb-4 pb-2">Cuando transferimos Datos personales fuera de México, tomamos las medidas legales requeridas para garantizar que se implementen las medidas de seguridad adecuadas para proteger tus Datos personales. Esto incluye el uso de Cláusulas contractuales tipo emitidas en virtud de la Decisión de Ejecución (UE) 2021/914 de la Comisión, de 4 de junio de 2021, del Parlamento Europeo y del Consejo. Encontrarás las Cláusulas contractuales estándar prefirmadas de Atemporal e información adicional en el Acuerdo de procesamiento de datos del organizador.</p>
            <h5 className="h5">Retención de datos personales</h5>
            <p className="mb-4 pb-2">Conservamos tus Datos personales durante el tiempo que sea necesario para proporcionarte nuestros Servicios, o para otros fines importantes como el cumplimiento de obligaciones legales, la resolución de disputas y la aplicación de nuestros acuerdos.</p>
            <p className="mb-4 pb-2">Si tienes una cuenta con nosotros, generalmente conservaremos tus Datos personales durante un periodo de noventa (90) días después de que hayas solicitado que tu cuenta se cierre o si ha estado inactiva durante siete (7) años.</p>
            <h5 className="h5">Tus derechos.</h5>
            <p className="mb-4 pb-2">La ley de protección de datos te otorga derechos con respecto a los Datos personales que tenemos sobre ti, incluido el derecho a solicitar una copia de los Datos personales, solicitar que rectifiquemos, restrinjamos o eliminemos tus Datos personales, objetar a los perfiles y cancelar la suscripción de comunicaciones de marketing.</p>
            <p className="mb-4 pb-2">En la mayoría de los casos, puedes ejercer estos derechos iniciando sesión y visitando la página Mi cuenta o cambiando la &#34;configuración de cookies&#34; en tu navegador (consulta nuestra Declaración de cookies para obtener más información). Si no encuentras lo que estás buscando en la página Mi cuenta, contáctanos usando la información de contacto establecida en la Sección 15 anterior. Ten en cuenta que las solicitudes para ejercer los derechos de protección de datos serán evaluadas caso por caso. Puede haber circunstancias en las que no se nos exija legalmente que cumplamos con tu solicitud debido a las leyes en tu jurisdicción o debido a las exenciones previstas en la legislación de protección de datos. Si tienes una reclamación sobre cómo manejamos tus Datos personales, ponte en contacto con nosotros tal como se establece en la Sección 15 para explicarlo. Si no estás conforme con la forma en que hemos intentado resolver tu reclamación, puedes comunicarte con la autoridad de protección de datos correspondiente.</p>
            <h5 className="h5">Atemporal como controlador de datos y procesador de datos</h5>
            <p className="mb-4 pb-2">La ley de protección de datos de la UE establece una distinción entre organizaciones que procesan Datos personales para sus propios fines (conocidos como &#34;controladores de datos&#34;) y organizaciones que procesan Datos personales en nombre de otras organizaciones (conocidos como &#34;procesadores de datos&#34;). Si tienes preguntas o reclamaciones sobre cómo se manejan tus Datos personales, debes dirigirlas siempre al controlador de datos relevante, ya que ellos son los principales responsables de tus Datos personales.</p>
            <p className="mb-4 pb-2">Atemporal puede actuar como un controlador de datos o un procesador de datos con respecto a tus Datos personales, dependiendo de las circunstancias.</p>
            <p className="mb-4 pb-2">Por ejemplo, si creas una cuenta con nosotros para organizar tus eventos, Atemporal será un controlador de datos con respecto a los Datos personales que proporciones como parte de tu cuenta. También seremos un controlador de datos de los Datos personales que hayamos obtenido sobre el uso de las Aplicaciones o las Propiedades de Atemporal, que podrían relacionarse con Organizadores o Consumidores. Usamos esto para realizar investigaciones y análisis para ayudar a comprender y prestar un mejor servicio a los Usuarios de los Servicios, así como para mejorar nuestra plataforma y proporcionarte recomendaciones más específicas sobre eventos que creemos que pueden ser de tu interés.</p>
            <p className="mb-4 pb-2">Sin embargo, si te registras para un evento como Consumidor, procesaremos tus Datos personales para ayudar a gestionar ese evento en nombre del Organizador (por ejemplo, enviando correos electrónicos de confirmación, promociones y comentarios, procesamiento de pagos, etc.) y para ayudar al objetivo del Organizador y a que comprenda el éxito de la planificación de sus eventos y de sus eventos (por ejemplo, proporcionar informes de eventos, usar análisis para obtener información sobre la efectividad de varios canales de ventas, etc.). En estas circunstancias, Atemporal simplemente proporciona las herramientas para los Organizadores; Atemporal no decide qué Datos personales solicitar en los formularios de registro, ni es responsable de la exactitud continua de los Datos personales proporcionados. Por lo tanto, cualquier pregunta que puedas tener relacionada con tus Datos personales y tus derechos bajo la ley de protección de datos debe dirigirse al Organizador como el controlador de datos, no a Atemporal.</p>
            </div>
          </div>
      </div>
      </section>
  )
}
